[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][Security.SecureString]$AdministrativeDatabaseUrl,
    [Parameter(Mandatory=$true)][string]$PoolerHost,
    [Parameter(Mandatory=$true)][int]$PoolerPort,
    [Parameter(Mandatory=$true)][string]$PoolerDatabase,
    [Parameter(Mandatory=$true)][string]$PoolerUser,
    [Parameter(Mandatory=$true)][string]$PoolerHostSuffix,
    [string]$DisposableRoleName='',
    [string]$ValidUntilUtc='',
    [Parameter(Mandatory=$true)][string]$ExpectedDatabaseName,
    [Parameter(Mandatory=$true)][string]$ExpectedProjectReference,
    [Parameter(Mandatory=$true)][string]$ExpectedRuntimeRoleName,
    [Parameter(Mandatory=$true)][string]$ExpectedRuntimeRoleOid,
    [Parameter(Mandatory=$true)][string]$ExpectedTargetRegprocedure,
    [Parameter(Mandatory=$true)][string]$ExpectedTargetOid,
    [Parameter(Mandatory=$true)][string]$ExpectedFunctionOwner,
    [Parameter(Mandatory=$true)][string]$OperatorConfirmation,
    [Parameter(Mandatory=$true)][string]$TranscriptDebugConfirmation,
    [ValidateSet('require')][string]$RequiredTlsMode='require',
    [ValidateRange(2,3600)][int]$ProcessTimeoutSeconds=300,
    [ValidateRange(50,9999)][int]$LockTimeoutMilliseconds=1000,
    [ValidateRange(100,29999)][int]$StatementTimeoutMilliseconds=5000,
    [ValidateRange(101,59999)][int]$ControllerTimeoutMilliseconds=15000,
    [ValidateRange(50,9999)][int]$CheckoutTimeoutMilliseconds=2000
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'
$Utf8NoBom=New-Object Text.UTF8Encoding($false,$true)
$RunId='A2.4E.S6-'+[DateTime]::UtcNow.ToString('yyyyMMddTHHmmssfffZ')
$LocalProjectReference='afex-a24e-pg17'
$ExpectedMatrixHash='b4f7f6eadf1b532a23d3882db324909de03011099c206282dee0ad8dae63cc58'
$ExpectedEngineHash='f12fda88d47da44f3c6504af3825a3abf7c000ee67b9c0bdef4159eea00f7cdf'
$ExpectedCreateHash='313072c41afb6ec9784386c8238eb6c268a042650ab1396410d6e5514ee089bf'
$ExpectedGeneratorHash='74e318edcb0b9403ddfcddb50b13f8c0814b0ed082d09ca48407cf7c1881f954'
$ExpectedRoleAttestationHash='c0257bedceea45d9e394c264a30c118747a6f126797405f219bfe578f5908cc3'
$ExpectedCleanupHash='0a324b066f126207a489eb4c00836ca770f786b97a91052dd5fb799f61ea874b'
$ExpectedPostCleanupHash='6a7ff904c3055cb45b2411cce70c918167fac132e704c13ca2e7bf7ba8abf009'
$ExpectedHarnessHash='8196a4bcac2aa8fff1bd4fb9a70d0685535cdfdb44de3ae93ae09646b1101eba'
$CreateMarker='A24E2A_900_DISPOSABLE_LOGIN_CREATE_COMPLETE'
$HarnessMarker='A24E5D_900_DISPOSABLE_LOGIN_HARNESS_COMPLETE'
$PgPassPath=$null;$RuntimePgPassPath=$null;$Credential=$null;$PasswordCopy=$null;$Mutex=$null;$MutexHeld=$false;$RoleMayExist=$false;$TrustedOid=$null;$EngineState=$null;$EvidenceDirectory=$null;$StagingDirectory=$null;$ExecutionError=$null;$CleanupError=$null;$CleanupErrorRecord=$null
$SecretNeedles=New-Object 'Collections.Generic.List[byte[]]'
$ObservedArtifacts=@{}

function Get-NormalizedPath([string]$Path){[IO.Path]::GetFullPath($Path).TrimEnd('\')}
function Write-Utf8([string]$Path,[AllowEmptyString()][string]$Text){[IO.File]::WriteAllText($Path,$Text,$script:Utf8NoBom)}
function Get-RepositoryRoot {
    $cursor=[IO.DirectoryInfo](Get-NormalizedPath $PSScriptRoot)
    while($null-ne$cursor){if((Test-Path (Join-Path $cursor.FullName '.git'))-and(Test-Path (Join-Path $cursor.FullName 'package.json'))){$root=Get-NormalizedPath $cursor.FullName;$gitRoot=(&git -C $root rev-parse --show-toplevel 2>$null).Trim();if($LASTEXITCODE-ne0-or(Get-NormalizedPath $gitRoot)-cne$root){throw 'REPOSITORY_ROOT_PROOF_FAILED'};return $root};$cursor=$cursor.Parent}
    throw 'REPOSITORY_ROOT_NOT_FOUND'
}
function Assert-Hash([string]$Path,[string]$Expected){if(-not(Test-Path $Path -PathType Leaf)){throw 'ARTIFACT_MISSING'};$actual=(Get-FileHash $Path -Algorithm SHA256).Hash.ToLowerInvariant();if($actual-cne$Expected){throw 'ARTIFACT_HASH_MISMATCH'};$actual}
function ConvertFrom-Secure([Security.SecureString]$Value){$p=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($Value);try{[Runtime.InteropServices.Marshal]::PtrToStringBSTR($p)}finally{[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($p)}}
function Add-SecretNeedle([string]$Value){if(-not[String]::IsNullOrEmpty($Value)){$bytes=[Text.Encoding]::UTF8.GetBytes($Value);if($bytes.Length){$script:SecretNeedles.Add($bytes)}}}
function Test-SafeText([string]$Text){if($Text-match'(?i)postgres(?:ql)?://\S+|SCRAM-SHA-256\$|\bBearer\s+\S+|\beyJ[A-Za-z0-9_-]{20,}\.'){return $false};foreach($needle in $SecretNeedles){$value=[Text.Encoding]::UTF8.GetString($needle);if($value.Length-and$Text.Contains($value)){return $false}};$true}
function Protect-PgPass([string]$Value){$Value.Replace('\','\\').Replace(':','\:')}
function New-PgPass([string]$HostName,[string]$Port,[string]$Database,[string]$User,[string]$Password){$path=Join-Path ([IO.Path]::GetTempPath()) ('afex-a24e-s6-'+[Guid]::NewGuid().ToString('N')+'.pgpass');$line=((@($HostName,$Port,$Database,$User,$Password)|%{Protect-PgPass $_})-join':')+"`n";Write-Utf8 $path $line;$acl=New-Object Security.AccessControl.FileSecurity;$acl.SetAccessRuleProtection($true,$false);$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User;$acl.AddAccessRule((New-Object Security.AccessControl.FileSystemAccessRule($sid,'FullControl','Allow')));[IO.File]::SetAccessControl($path,$acl);$path}
function ConvertTo-PsqlLiteral([string]$Value){if($Value.IndexOf([char]0)-ge0-or$Value-match"[`r`n]"){throw 'PSQL_VALUE_INVALID'};"'"+$Value.Replace("'","''")+"'"}
function Get-PsqlIncludePath([string]$SqlPath){if([String]::IsNullOrWhiteSpace($SqlPath)-or$SqlPath.IndexOf([char]0)-ge0-or$SqlPath-match"[`r`n;']"){throw 'PSQL_INCLUDE_PATH_INVALID'};if(-not[IO.Path]::IsPathRooted($SqlPath)){throw 'PSQL_INCLUDE_PATH_NOT_ABSOLUTE'};if(@($SqlPath-split'[\\/]'|?{$_-ceq'..'}).Count){throw 'PSQL_INCLUDE_PATH_TRAVERSAL'};$full=[IO.Path]::GetFullPath($SqlPath);$root=[IO.Path]::GetFullPath($RepositoryRoot).TrimEnd([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar);$prefix=$root+[IO.Path]::DirectorySeparatorChar;if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)-or[IO.Path]::GetExtension($full)-cne'.sql'){throw 'PSQL_INCLUDE_PATH_OUTSIDE_CONTRACT'};if(-not(Test-Path -LiteralPath $full -PathType Leaf)){throw 'PSQL_INCLUDE_PATH_MISSING'};$full.Replace('\','/')}
function New-PsqlIncludeLine([string]$SqlPath){'\i {0}'-f(ConvertTo-PsqlLiteral (Get-PsqlIncludePath $SqlPath))}
function New-PsqlInput([hashtable]$Variables,[string]$SqlPath){$lines=New-Object 'Collections.Generic.List[string]';$lines.Add('\set ECHO none');$lines.Add('\pset tuples_only on');$lines.Add('\pset format unaligned');$lines.Add('\pset fieldsep |');foreach($name in @($Variables.Keys|Sort-Object)){if($name-cnotmatch'^[a-z][a-z0-9_]*$'){throw 'PSQL_VARIABLE_INVALID'};$lines.Add(('\set {0} {1}'-f$name,(ConvertTo-PsqlLiteral ([string]$Variables[$name]))))};$lines.Add((New-PsqlIncludeLine $SqlPath));($lines-join"`n")+"`n"}
function Get-Executable([string]$Name,[string[]]$Leaves){$found=@(Get-Command $Name -All|?{$_.CommandType-eq'Application'-and[IO.Path]::GetFileName($_.Source)-in$Leaves});if(@($found).Count-ne1){throw 'EXECUTABLE_RESOLUTION_INVALID'};Get-NormalizedPath $found[0].Source}
function Invoke-ProcessTransport([string]$Name,[string]$Executable,[string[]]$Arguments,[string]$InputText,[hashtable]$Environment){
    $stdoutPath=Join-Path $EvidenceDirectory ('transport/'+$Name+'.stdout.txt');$stderrPath=Join-Path $EvidenceDirectory ('transport/'+$Name+'.stderr.txt');$info=New-Object Diagnostics.ProcessStartInfo;$info.FileName=$Executable;$info.Arguments=(@($Arguments|%{if($_-match'[\s"]'){'"'+$_.Replace('"','\"')+'"'}else{$_}})-join' ');$info.UseShellExecute=$false;$info.CreateNoWindow=$true;$info.RedirectStandardInput=$true;$info.RedirectStandardOutput=$true;$info.RedirectStandardError=$true
    foreach($key in @($Environment.Keys)){$info.EnvironmentVariables[$key]=[string]$Environment[$key]}
    $p=New-Object Diagnostics.Process;$p.StartInfo=$info;$started=$false;$timedOut=$false;$terminationIncomplete=$false;$exit=$null;$stdout='';$stderr='';try{$started=$p.Start();if(-not$started){throw 'PROCESS_LAUNCH_FAILED'};if($InputText.Length){$p.StandardInput.Write($InputText)};$p.StandardInput.Close();if(-not$p.WaitForExit($ProcessTimeoutSeconds*1000)){$timedOut=$true;try{$p.Kill()}catch{$terminationIncomplete=$true};if(-not$terminationIncomplete){$p.WaitForExit()}};$stdout=$p.StandardOutput.ReadToEnd();$stderr=$p.StandardError.ReadToEnd();if(-not$terminationIncomplete){$exit=[long]$p.ExitCode}}finally{$p.Dispose()}
    if(-not(Test-SafeText $stdout)-or-not(Test-SafeText $stderr)){Write-Utf8 $stdoutPath 'redaction_result=FAIL';Write-Utf8 $stderrPath 'redaction_result=FAIL';$redactionRejected=$true}else{Write-Utf8 $stdoutPath $stdout;Write-Utf8 $stderrPath $stderr;$redactionRejected=$false}
    [pscustomobject][ordered]@{name=$Name;started=$started;timed_out=$timedOut;termination_incomplete=$terminationIncomplete;exit_code=$exit;stdout=$stdout;stderr=$stderr;stdout_sha256=(Get-FileHash $stdoutPath -Algorithm SHA256).Hash.ToLowerInvariant();stderr_sha256=(Get-FileHash $stderrPath -Algorithm SHA256).Hash.ToLowerInvariant();redaction_rejected=$redactionRejected;recorded_utc=[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ss.fffZ')}
}
function New-ProcessObservation([string]$Stage,$Transport,[string]$Marker,[bool]$SchemaFailed=$false){[pscustomobject][ordered]@{run_id=$RunId;stage_name=$Stage;dependency_block=$false;launch_failed=[bool](-not$Transport.started);wrapper_failed=$false;timed_out=[bool]$Transport.timed_out;termination_incomplete=[bool]($null-ne$Transport.PSObject.Properties['termination_incomplete']-and$Transport.termination_incomplete);exit_code=$Transport.exit_code;marker_count=[long]@([regex]::Matches($Transport.stdout,('(?m)^'+[regex]::Escape($Marker)+'\s*$'))).Count;stdout_redaction_rejected=[bool]$Transport.redaction_rejected;stderr_redaction_rejected=[bool]$Transport.redaction_rejected;harness_schema_failed=$SchemaFailed;harness_incomplete=$false;stdout_sha256=$Transport.stdout_sha256;stderr_sha256=$Transport.stderr_sha256;recorded_utc=$Transport.recorded_utc}}
function Invoke-EngineProcess([string]$Stage,$Transport,[string]$Marker,[bool]$SchemaFailed=$false){$result=Invoke-EeeProcessObservation $script:EngineState (New-ProcessObservation $Stage $Transport $Marker $SchemaFailed);$script:EngineState=$result.state;$result.outcome}
function Get-CommonVariables { @{run_id=$RunId;disposable_role_name=$DisposableRoleName;expected_database_name=$ExpectedDatabaseName;expected_project_reference=$ExpectedProjectReference;actual_project_reference=$LocalProjectReference;expected_postgres_major='17';expected_runtime_role_name=$ExpectedRuntimeRoleName;expected_runtime_role_oid=$ExpectedRuntimeRoleOid;expected_target_regprocedure=$ExpectedTargetRegprocedure;expected_target_oid=$ExpectedTargetOid;expected_function_owner=$ExpectedFunctionOwner} }
function Invoke-CreateTransport([string]$SqlPath,[string]$Verifier,[string]$ValidUntil){$vars=Get-CommonVariables;$vars.disposable_role_scram_verifier=$Verifier;$vars.valid_until_utc=$ValidUntil;$input=New-PsqlInput $vars $SqlPath;Invoke-ProcessTransport '020-create' $Psql @('-X','--no-password','--set=ON_ERROR_STOP=1','--host',$AdminHost,'--port',$AdminPort,'--username',$AdminUser,'--dbname',$AdminDatabase) $input @{PGPASSFILE=$PgPassPath;PGSSLMODE='require'}}
function Invoke-LifecycleHarness([string]$Operation,[string]$SqlPath,[string]$Oid){$dir=Join-Path $EvidenceDirectory ('transport/'+$Operation.ToLowerInvariant());[void](New-Item -ItemType Directory -Path $dir);$runtime=$Operation-ceq'RUNTIME_TEST';$env=@{A24E5D_OPERATION=$Operation;A24E5D_RUN_ID=$RunId;A24E5D_DISPOSABLE_ROLE_NAME=$DisposableRoleName;A24E5D_EXPECTED_DATABASE_NAME=$ExpectedDatabaseName;A24E5D_EXPECTED_POSTGRES_MAJOR='17';A24E5D_PSQL_PATH=$Psql;A24E5D_EVIDENCE_DIRECTORY=$dir;A24E5D_TIMEOUT_MS=[string]($ProcessTimeoutSeconds*1000);PGPASSFILE=$(if($runtime){$RuntimePgPassPath}else{$PgPassPath});PGHOST=$(if($runtime){$PoolerHost}else{$AdminHost});PGPORT=$(if($runtime){[string]$PoolerPort}else{$AdminPort});PGUSER=$(if($runtime){$DisposableRoleName}else{$AdminUser});PGDATABASE=$(if($runtime){$PoolerDatabase}else{$AdminDatabase})};if(-not$runtime){$env.A24E5D_SQL_PATH=Get-PsqlIncludePath $SqlPath};if($Operation-ceq'ROLE_ATTESTATION'){$env.A24E5D_EXPECTED_RUNTIME_ROLE_NAME=$ExpectedRuntimeRoleName;$env.A24E5D_EXPECTED_RUNTIME_ROLE_OID=$ExpectedRuntimeRoleOid;$env.A24E5D_EXPECTED_TARGET_REGPROCEDURE=$ExpectedTargetRegprocedure;$env.A24E5D_EXPECTED_TARGET_OID=$ExpectedTargetOid;$env.A24E5D_EXPECTED_FUNCTION_OWNER=$ExpectedFunctionOwner}elseif($runtime){$env.A24E5D_EXPECTED_RUNTIME_ROLE_NAME=$ExpectedRuntimeRoleName;$env.A24E5D_EXPECTED_DISPOSABLE_ROLE_OID=$Oid}else{$env.A24E5D_EXPECTED_DISPOSABLE_ROLE_OID=$Oid;if($Operation-ceq'CLEANUP'){$env.A24E5D_EXPECTED_RUNTIME_ROLE_NAME=$ExpectedRuntimeRoleName;$env.A24E5D_EXPECTED_RUNTIME_ROLE_OID=$ExpectedRuntimeRoleOid;$env.A24E5D_ADVISORY_LOCK_IDENTITY="$ExpectedProjectReference|$ExpectedDatabaseName|$DisposableRoleName|$Oid|$RunId"}};Invoke-ProcessTransport ('lifecycle-'+$Operation.ToLowerInvariant()) $Node @($HarnessPath) '' $env}
function Invoke-RoleLookupTransport { $vars=@{run_id=$RunId;disposable_role_name=$DisposableRoleName};$sql="BEGIN TRANSACTION READ ONLY;`nSELECT 'A24E_ROLE_LOOKUP|' || :'run_id' || '|' || :'disposable_role_name' || '|' || COALESCE((SELECT oid::text FROM pg_catalog.pg_roles WHERE rolname = :'disposable_role_name'),'0') || '|PASS';`nROLLBACK;`nSELECT 'A24E_ROLE_LOOKUP_COMPLETE';`n";$input=(New-PsqlInput $vars $CreatePath).Replace((New-PsqlIncludeLine $CreatePath),$sql.TrimEnd());Invoke-ProcessTransport 'ambiguous-create-role-lookup' $Psql @('-X','--no-password','--set=ON_ERROR_STOP=1','--host',$AdminHost,'--port',$AdminPort,'--username',$AdminUser,'--dbname',$AdminDatabase) $input @{PGPASSFILE=$PgPassPath;PGSSLMODE='require'} }
function Get-LookupOid([string]$Text){$m=[regex]::Matches($Text,'(?m)^A24E_ROLE_LOOKUP\|[^|]+\|[^|]+\|([0-9]+)\|PASS\s*$');if(@($m).Count-ne1){throw 'ROLE_LOOKUP_RESULT_INVALID'};[long]$m[0].Groups[1].Value}
function Get-RoleOid([string]$Text,[string]$ExpectedRunId,[string]$ExpectedRoleName){$lines=@($Text-split"`r?`n");$markers=@($lines|Where-Object{$_-ceq'A24E5A_900_DISPOSABLE_LOGIN_ROLE_ATTESTATION_COMPLETE'});if(@($markers).Count-ne1){throw 'ROLE_ATTESTATION_COMPLETION_MARKER_INVALID'};$rows=@($lines|Where-Object{$_-cmatch'^A24E4A_ROLE_IDENTITY\|'});if(@($rows).Count-ne1){throw 'ROLE_ATTESTATION_IDENTITY_ROW_COUNT_INVALID'};$fields=@($rows[0]-split'\|');if(@($fields).Count-ne5-or$fields[0]-cne'A24E4A_ROLE_IDENTITY'){throw 'ROLE_ATTESTATION_IDENTITY_ROW_INVALID'};if($fields[1]-cne$ExpectedRunId){throw 'ROLE_ATTESTATION_RUN_ID_MISMATCH'};if($fields[2]-cne$ExpectedRoleName){throw 'ROLE_ATTESTATION_ROLE_NAME_MISMATCH'};if($fields[3]-cnotmatch'^[1-9][0-9]*$'){throw 'ROLE_ATTESTATION_OID_INVALID'};if($fields[4]-cne'PASS'){throw 'ROLE_ATTESTATION_IDENTITY_STATUS_INVALID'};[long]$fields[3]}
function New-SafeArtifact([string]$Schema,[hashtable]$Fields){$row=[ordered]@{schema_version=$Schema;run_id=$RunId};foreach($key in @($Fields.Keys|Sort-Object)){$row[$key]=$Fields[$key]};ConvertTo-EeeCanonicalJsonBytes ([pscustomobject]$row)}
function New-SourceStore {
    $profile=Get-EeeEngineFinalizationProfile $EngineState;$source=@{};$transition=ConvertTo-EeeJsonLinesBytes @($EngineState.transition_records);$classification=ConvertTo-EeeJsonLinesBytes @($EngineState.classification_records);$stages=ConvertTo-EeeJsonLinesBytes @($EngineState.stage_authorities)
    foreach($id in @($profile.required_source_logical_ids)){switch -CaseSensitive($id){'transition_ledger'{$source[$id]=$transition}'classification_ledger'{$source[$id]=$classification}'stage_ledger'{$source[$id]=$stages}default{if(-not$ObservedArtifacts.ContainsKey($id)){
        $observedKeys=[string[]]@($ObservedArtifacts.Keys|ForEach-Object{[string]$_});[Array]::Sort($observedKeys,[StringComparer]::Ordinal)
        $diagnostic=[pscustomobject][ordered]@{schema_version='A24E_S6_SOURCE_SET_MISSING_V1';run_id=$RunId;profile_id=$profile.profile_id;engine_current_state=$EngineState.current_state;missing_logical_id=[string]$id;required_source_logical_ids=@($profile.required_source_logical_ids);generated_ledger_ids=@('classification_ledger','stage_ledger','transition_ledger');observed_artifact_keys=@($observedKeys);recorded_utc=$RecordedUtc;result='FAIL'}
        Write-Utf8 (Join-Path $EvidenceDirectory 'transport/source-set-missing.json') ((ConvertTo-EeeCanonicalJson $diagnostic)+"`n")
        $safeId=$(if(([string]$id)-cmatch'^[a-z0-9_]+$'){([string]$id).ToUpperInvariant()}else{'UNKNOWN_ID'});throw ('ENGINE_REQUIRED_SOURCE_MISSING_'+$safeId)
    };$source[$id]=[byte[]]$ObservedArtifacts[$id].Clone()}}}
    [pscustomobject][ordered]@{profile_id=$profile.profile_id;source=$source}
}
function New-ControlSet {
    $derived=New-SourceStore;$source=$derived.source;$red=New-EeeRecursiveRedactionPrecommit $RunId $derived.profile_id $source @($SecretNeedles) $RecordedUtc;$ledgers=@{transition_ledger=$source.transition_ledger;classification_ledger=$source.classification_ledger;stage_ledger=$source.stage_ledger};$binding=New-EeeLedgerBindingSet $RunId $ledgers $RecordedUtc;$registry=New-EeeArtifactRegistryRecord $RunId $derived.profile_id $RecordedUtc;$subject=@{};foreach($id in $source.Keys){$subject[$id]=[byte[]]$source[$id].Clone()};$subject.recursive_redaction_precommit=ConvertTo-EeeCanonicalJsonBytes $red;$subject.ledger_binding_set=ConvertTo-EeeCanonicalJsonBytes $binding;$subject.artifact_registry=ConvertTo-EeeCanonicalJsonBytes $registry;$inventory=New-EeeExactInventory $RunId $derived.profile_id $subject $RecordedUtc;$control=New-EeePrecommitControlInventory $RunId $derived.profile_id @{recursive_redaction_precommit=$subject.recursive_redaction_precommit;ledger_binding_set=$subject.ledger_binding_set;artifact_registry=$subject.artifact_registry;evidence_inventory=ConvertTo-EeeCanonicalJsonBytes $inventory} $RecordedUtc;$reconciliation=New-EeeReconciliationArtifact $EngineState $derived.profile_id $subject $red $binding $registry $inventory $control $RecordedUtc;New-EeeControlArtifactSet $EngineState $derived.profile_id $source @($SecretNeedles) $reconciliation $RecordedUtc
}
function Publish-EnginePlan($Finalization,$Plan){
    $receipts=@();foreach($command in @($Plan.commands)){$bytes=[byte[]]$Finalization.publication_artifact_bytes.($command.logical_id);$source=$command.source_staging_path;$destination=$command.destination_path;[void](New-Item -ItemType Directory -Path ([IO.Path]::GetDirectoryName($source)) -Force);[IO.File]::WriteAllBytes($source,$bytes);$sourceBytes=[IO.File]::ReadAllBytes($source);$sourceHash=Get-EeeSha256Hex $sourceBytes;$destinationAbsent=-not(Test-Path $destination);$published=$false;$collision=$false;if($destinationAbsent){[void](New-Item -ItemType Directory -Path ([IO.Path]::GetDirectoryName($destination)) -Force);try{[IO.File]::Move($source,$destination);$published=$true}catch{$collision=$true}};$destinationBytes=$(if($published){[IO.File]::ReadAllBytes($destination)}else{[byte[]]@()});$receipts+=,[pscustomobject][ordered]@{schema_version='A24E_FINAL_V4_TRANSPORT_RECEIPT';run_id=$RunId;command_sequence=[long]$command.command_sequence;logical_id=$command.logical_id;command_hash=Get-EeeSha256Hex(ConvertTo-EeeCanonicalJsonBytes $command);attempted=$true;source_reread_succeeded=$sourceHash-ceq$command.expected_sha256;source_sha256=$sourceHash;source_size_bytes=[long]$sourceBytes.Length;destination_was_absent=$destinationAbsent;publish_succeeded=$published;destination_reread_succeeded=$published;destination_sha256=$(if($published){Get-EeeSha256Hex $destinationBytes}else{'0'*64});destination_size_bytes=[long]$destinationBytes.Length;create_once_preserved=$destinationAbsent-and$published;overwrite_occurred=$false;same_volume_preserved=[IO.Path]::GetPathRoot($source)-ceq[IO.Path]::GetPathRoot($destination);collision_detected=$collision;recorded_utc=[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ss.fffZ');failure_code=$(if($published){'NONE'}else{'PUBLICATION_FAILED'})}}
    return $receipts
}

$RepositoryRoot=Get-RepositoryRoot
if($PSVersionTable.PSVersion.Major-ne5-or$PSVersionTable.PSVersion.Minor-ne1){throw 'POWERSHELL_51_REQUIRED'}
if($OperatorConfirmation-cne'A24E4A_PRODUCTION_EXECUTION_APPROVED'-or$TranscriptDebugConfirmation-cne'A24E4A_TRANSCRIPT_AND_DEBUG_DISABLED'){throw 'OPERATOR_CONFIRMATION_MISSING'}
if($ExpectedProjectReference-cne$LocalProjectReference){throw 'LOCAL_PROJECT_REFERENCE_MISMATCH'}
if($RequiredTlsMode-cne'require'-or$PoolerPort-ne6543-or-not($PoolerHost.ToLowerInvariant().EndsWith($PoolerHostSuffix.TrimStart('.').ToLowerInvariant()))){throw 'POOLER_CONTRACT_INVALID'}
if(@(git -C $RepositoryRoot diff --cached --name-only).Count){throw 'STAGED_FILES_PRESENT'}
$MatrixPath=Join-Path $RepositoryRoot 'runtime-integration/A2.4E.FINAL-TRUSTED-IDENTITY-FINAL-AUTHORITY-MATRIX.md';$EnginePath=Join-Path $RepositoryRoot 'runtime-integration/engine/A2.4E.ExecutionEvidenceEngine.psm1';$CreatePath=Join-Path $RepositoryRoot 'database-reconciliation/core-v2/P2D/A2.4E.2A-DISPOSABLE-LOGIN-CREATE.sql';$GeneratorPath=Join-Path $RepositoryRoot 'A2.4E.SCRAM-VERIFIER-GENERATOR.ps1';$RolePath=Join-Path $RepositoryRoot 'runtime-integration/A2.4E.5A-DISPOSABLE-LOGIN-ROLE-ATTESTATION.sql';$CleanupPath=Join-Path $RepositoryRoot 'runtime-integration/A2.4E.5B-DISPOSABLE-LOGIN-CLEANUP.sql';$PostPath=Join-Path $RepositoryRoot 'runtime-integration/A2.4E.5C-DISPOSABLE-LOGIN-POST-CLEANUP-ATTESTATION.sql';$HarnessPath=Join-Path $RepositoryRoot 'runtime-integration/A2.4E.5D-DISPOSABLE-LOGIN-HARNESS.mjs'
[void](Assert-Hash $MatrixPath $ExpectedMatrixHash);[void](Assert-Hash $EnginePath $ExpectedEngineHash);[void](Assert-Hash $CreatePath $ExpectedCreateHash);[void](Assert-Hash $GeneratorPath $ExpectedGeneratorHash);[void](Assert-Hash $RolePath $ExpectedRoleAttestationHash);[void](Assert-Hash $CleanupPath $ExpectedCleanupHash);[void](Assert-Hash $PostPath $ExpectedPostCleanupHash);[void](Assert-Hash $HarnessPath $ExpectedHarnessHash)
Import-Module $EnginePath -Force -ErrorAction Stop
$Psql=Get-Executable psql @('psql.exe');$Node=Get-Executable node @('node.exe')
$EvidenceRoot=Join-Path $RepositoryRoot 'database-reconciliation/core-v2/P2D/evidence';if(-not(Test-Path $EvidenceRoot)){[void](New-Item -ItemType Directory $EvidenceRoot)};&git -C $RepositoryRoot check-ignore -q -- 'database-reconciliation/core-v2/P2D/evidence/';if($LASTEXITCODE-ne0){throw 'EVIDENCE_ROOT_NOT_IGNORED'}
$EvidenceDirectory=Join-Path $EvidenceRoot $RunId;$StagingDirectory=Join-Path $EvidenceRoot ('.staging-'+$RunId);[void](New-Item -ItemType Directory -Path (Join-Path $EvidenceDirectory 'transport') -Force);[void](New-Item -ItemType Directory -Path $StagingDirectory)
$mutexName='Local\AFEX_A24E_S6_'+(Get-EeeSha256Hex([Text.Encoding]::UTF8.GetBytes($RepositoryRoot))).Substring(0,24);$Mutex=New-Object Threading.Mutex($false,$mutexName);$MutexHeld=$Mutex.WaitOne(0);if(-not$MutexHeld){throw 'EXECUTION_LOCK_BUSY'}
$EngineState=New-EeeExecutionState $RunId;$RecordedUtc=[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ss.fffZ')
try{
    $empty=New-SafeArtifact 'A24E_S6_LOCAL_OBSERVATION' @{stage='preflight';result='PASS'};$emptyPath=Join-Path $EvidenceDirectory 'transport/preflight.txt';[IO.File]::WriteAllBytes($emptyPath,$empty);$h=(Get-FileHash $emptyPath -Algorithm SHA256).Hash.ToLowerInvariant();$synthetic=[pscustomobject][ordered]@{name='preflight';started=$true;timed_out=$false;exit_code=[long]0;stdout='A24E_S6_PREFLIGHT';stderr='';stdout_sha256=$h;stderr_sha256=$h;redaction_rejected=$false;recorded_utc=$RecordedUtc};[void](Invoke-EngineProcess 'preflight' $synthetic 'A24E_S6_PREFLIGHT')
    if([String]::IsNullOrEmpty($DisposableRoleName)){$DisposableRoleName='afex_core_test_login_'+[DateTime]::UtcNow.ToString('yyyyMMddHHmmss')+'_'+[Guid]::NewGuid().ToString('N').Substring(0,8)};if($DisposableRoleName-cnotmatch'^afex_core_test_login_[0-9]{14}_[0-9a-f]{8}$'){throw 'ROLE_NAME_INVALID'};if([String]::IsNullOrEmpty($ValidUntilUtc)){$ValidUntilUtc=[DateTimeOffset]::UtcNow.AddMinutes(60).ToString('yyyy-MM-ddTHH:mm:ssZ')}
    $plain=ConvertFrom-Secure $AdministrativeDatabaseUrl;Add-SecretNeedle $plain;if($plain-match'%(?![0-9A-Fa-f]{2})'){throw 'ADMIN_URI_ENCODING_INVALID'};$uri=[Uri]$plain;$separator=$uri.UserInfo.IndexOf(':');if($separator-le0-or$uri.Scheme-cnotin@('postgres','postgresql')){throw 'ADMIN_URI_INVALID'};$AdminUser=[Uri]::UnescapeDataString($uri.UserInfo.Substring(0,$separator));$password=[Uri]::UnescapeDataString($uri.UserInfo.Substring($separator+1));Add-SecretNeedle $password;$AdminHost=$uri.Host;$AdminPort=$(if($uri.IsDefaultPort){'5432'}else{[string]$uri.Port});$AdminDatabase=[Uri]::UnescapeDataString($uri.AbsolutePath.TrimStart('/'));$PgPassPath=New-PgPass $AdminHost $AdminPort $AdminDatabase $AdminUser $password;$plain=$null;$password=$null;$uri=$null
    . $GeneratorPath;$Credential=New-AfexDisposableLoginCredential;$verifier=$Credential.GetScramVerifier();Add-SecretNeedle $verifier;$PasswordCopy=$Credential.GetPasswordSecureString();$runtimePassword=ConvertFrom-Secure $PasswordCopy;Add-SecretNeedle $runtimePassword;$RuntimePgPassPath=New-PgPass $PoolerHost ([string]$PoolerPort) $PoolerDatabase $DisposableRoleName $runtimePassword;$runtimePassword=$null;$credentialArtifact=New-SafeArtifact 'A24E_S6_CREDENTIAL_OBSERVATION' @{stage='credential';result='PASS'};$credentialPath=Join-Path $EvidenceDirectory 'transport/credential.txt';[IO.File]::WriteAllBytes($credentialPath,$credentialArtifact);$ch=(Get-FileHash $credentialPath -Algorithm SHA256).Hash.ToLowerInvariant();$credentialTransport=[pscustomobject][ordered]@{name='credential';started=$true;timed_out=$false;exit_code=[long]0;stdout='A24E_S6_CREDENTIAL';stderr='';stdout_sha256=$ch;stderr_sha256=$ch;redaction_rejected=$false;recorded_utc=[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ss.fffZ')};[void](Invoke-EngineProcess 'credential' $credentialTransport 'A24E_S6_CREDENTIAL')
    $create=Invoke-CreateTransport $CreatePath $verifier $ValidUntilUtc;$verifier=$null;$RoleMayExist=$create.started;$createOutcome=Invoke-EngineProcess 'create' $create $CreateMarker
    if($createOutcome.stage_result-ceq'PASS'){$parts=@($create.stdout-split"`r?`n"|?{$_-match'\|CREATED_PENDING_COMMIT\s*$'});if(@($parts).Count-ne1){throw 'CREATE_RESULT_INVALID'};$fields=$parts[0]-split'\|';if(@($fields).Count-lt3-or$fields[2]-cnotmatch'^[1-9][0-9]*$'){throw 'CREATE_OID_INVALID'};$TrustedOid=[long]$fields[2];$ObservedArtifacts.create_identity=New-SafeArtifact 'A24E_FINAL_V4_CREATE_IDENTITY' @{role_name=$DisposableRoleName;role_oid=$TrustedOid;source_artifact_sha256=$create.stdout_sha256;recorded_utc=$create.recorded_utc}}
    if($RoleMayExist-and$null-eq$TrustedOid){$lookup=Invoke-RoleLookupTransport;$lookupOutcome=Invoke-EngineProcess 'role_lookup' $lookup 'A24E_ROLE_LOOKUP_COMPLETE';if($lookupOutcome.stage_result-cne'PASS'){throw 'AMBIGUOUS_CREATE_LOOKUP_FAILED'};$discovered=Get-LookupOid $lookup.stdout;if($discovered-gt0){$TrustedOid=$discovered;$ObservedArtifacts.create_identity=New-SafeArtifact 'A24E_FINAL_V4_CREATE_IDENTITY' @{role_name=$DisposableRoleName;role_oid=$TrustedOid;source_artifact_sha256=$lookup.stdout_sha256;recorded_utc=$lookup.recorded_utc}}else{throw 'AMBIGUOUS_CREATE_ROLE_ABSENCE_REQUIRES_FAILURE_AUTHORITY'}}
    if($RoleMayExist-and$null-ne$TrustedOid){$att=Invoke-LifecycleHarness 'ROLE_ATTESTATION' $RolePath ([string]$TrustedOid);$attOutcome=Invoke-EngineProcess 'role_attestation' $att $HarnessMarker;if($attOutcome.stage_result-cne'PASS'){throw 'ROLE_ATTESTATION_PROCESS_NOT_PASS'};$attestationStdoutPath=Join-Path $EvidenceDirectory 'transport/role_attestation/stdout.txt';if(-not(Test-Path -LiteralPath $attestationStdoutPath -PathType Leaf)){throw 'ROLE_ATTESTATION_STDOUT_MISSING'};$attested=Get-RoleOid ([IO.File]::ReadAllText($attestationStdoutPath,$Utf8NoBom)) $RunId $DisposableRoleName;if($TrustedOid-ne$attested){throw 'ROLE_NAME_OID_CONFLICT'};$binding=Bind-EeeTrustedIdentity $EngineState ([pscustomobject][ordered]@{run_id=$RunId;source='ATTESTATION';role_name=$DisposableRoleName;role_oid=[long]$attested;source_artifact_sha256=$att.stdout_sha256;recorded_utc=$att.recorded_utc});if($null-eq$binding-or$null-eq$binding.state-or$null-eq$binding.trusted_identity-or-not(Test-EeeExecutionState $binding.state).valid-or-not$binding.state.identity_bound-or-not$binding.state.identity_authoritative-or$binding.state.role_name-cne$DisposableRoleName-or$binding.state.role_oid-ne$attested){throw 'ROLE_ATTESTATION_ENGINE_BINDING_INVALID'};$EngineState=$binding.state;$TrustedOid=$attested;$ObservedArtifacts.role_attestation_identity=New-SafeArtifact 'A24E_FINAL_V4_ROLE_ATTESTATION_IDENTITY' @{role_name=$DisposableRoleName;role_oid=$TrustedOid;source_artifact_sha256=$att.stdout_sha256;recorded_utc=$att.recorded_utc};$ObservedArtifacts.trusted_role_identity=ConvertTo-EeeCanonicalJsonBytes $binding.trusted_identity}
    if($EngineState.current_state-ceq'ROLE_ATTESTED'){if(-not$ObservedArtifacts.ContainsKey('role_attestation_identity')){throw 'ROLE_ATTESTATION_IDENTITY_ARTIFACT_MISSING'};if(-not$ObservedArtifacts.ContainsKey('trusted_role_identity')){throw 'TRUSTED_ROLE_IDENTITY_ARTIFACT_MISSING'};if(-not(Test-EeeExecutionState $EngineState).valid-or-not$EngineState.identity_bound-or-not$EngineState.identity_authoritative-or$EngineState.role_name-cne$DisposableRoleName-or$EngineState.role_oid-ne$TrustedOid){throw 'ROLE_ATTESTATION_ENGINE_BINDING_INVALID'};if($null-eq$TrustedOid-or$TrustedOid-le0){throw 'ROLE_ATTESTATION_TRUSTED_OID_INVALID'};$harness=Invoke-LifecycleHarness 'RUNTIME_TEST' '' ([string]$TrustedOid);[void](Invoke-EngineProcess 'harness' $harness $HarnessMarker)}
}catch{
    $ExecutionError=$true
    if($null-ne$EngineState-and(Test-EeeExecutionState $EngineState).valid){try{$rawException=[pscustomobject][ordered]@{stage_name='execution_boundary';exception_type=$_.Exception.GetType().FullName;exception_message=$_.Exception.Message;fully_qualified_error_id=$_.FullyQualifiedErrorId;script_stack_trace=[string]$_.ScriptStackTrace;recorded_utc=[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ss.fffZ')};$exceptionResult=Invoke-EeeExceptionObservation $EngineState $rawException;$EngineState=$exceptionResult.state}catch{$EngineState=$null}}
    throw
}finally{
    if($RoleMayExist-and$null-ne$TrustedOid){try{$cleanup=Invoke-LifecycleHarness 'CLEANUP' $CleanupPath ([string]$TrustedOid);$cleanupProcess=Invoke-EngineProcess 'cleanup' $cleanup $HarnessMarker;$cleanupObs=[pscustomobject][ordered]@{run_id=$RunId;process_outcome=$cleanupProcess;identity_match=$true;membership_removed=$cleanupProcess.stage_result-ceq'PASS';sessions_terminated=$cleanupProcess.stage_result-ceq'PASS';role_absent=$cleanupProcess.stage_result-ceq'PASS';ownership_absent=$cleanupProcess.stage_result-ceq'PASS';acl_absent=$cleanupProcess.stage_result-ceq'PASS';dependencies_absent=$cleanupProcess.stage_result-ceq'PASS';recorded_utc=$cleanup.recorded_utc};$cleanupResult=Invoke-EeeCleanupObservation $EngineState $cleanupObs;$EngineState=$cleanupResult.state;$ObservedArtifacts.cleanup_evidence=ConvertTo-EeeCanonicalJsonBytes $cleanupResult.evidence;if($cleanupResult.evidence.result-ceq'PASS'){$post=Invoke-LifecycleHarness 'POST_CLEANUP_ATTESTATION' $PostPath ([string]$TrustedOid);$postProcess=Invoke-EngineProcess 'post_cleanup' $post $HarnessMarker;$postObs=[pscustomobject][ordered]@{run_id=$RunId;process_outcome=$postProcess;identity_match=$true;role_absent=$postProcess.stage_result-ceq'PASS';sessions_absent=$postProcess.stage_result-ceq'PASS';memberships_absent=$postProcess.stage_result-ceq'PASS';ownership_absent=$postProcess.stage_result-ceq'PASS';acl_absent=$postProcess.stage_result-ceq'PASS';default_privileges_absent=$postProcess.stage_result-ceq'PASS';dependencies_absent=$postProcess.stage_result-ceq'PASS';baseline_unchanged=$postProcess.stage_result-ceq'PASS';recorded_utc=$post.recorded_utc};$postResult=Invoke-EeePostCleanupObservation $EngineState $postObs;$EngineState=$postResult.state;$ObservedArtifacts.post_cleanup_evidence=ConvertTo-EeeCanonicalJsonBytes $postResult.evidence}}catch{$CleanupError=$true;$CleanupErrorRecord=$_}}
    if($null-ne$Credential){$Credential.Dispose();$Credential=$null};if($null-ne$PasswordCopy){$PasswordCopy.Dispose();$PasswordCopy=$null};if($null-ne$RuntimePgPassPath-and(Test-Path $RuntimePgPassPath)){Remove-Item $RuntimePgPassPath -Force};if($null-ne$PgPassPath-and(Test-Path $PgPassPath)){Remove-Item $PgPassPath -Force}
}
$RecordedUtc=[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ss.fffZ')
if($CleanupError-and$null-ne$CleanupErrorRecord-and$null-ne$EngineState-and(Test-EeeExecutionState $EngineState).valid){try{$rawException=[pscustomobject][ordered]@{stage_name='cleanup_boundary';exception_type=$CleanupErrorRecord.Exception.GetType().FullName;exception_message=$CleanupErrorRecord.Exception.Message;fully_qualified_error_id=$CleanupErrorRecord.FullyQualifiedErrorId;script_stack_trace=[string]$CleanupErrorRecord.ScriptStackTrace;recorded_utc=$RecordedUtc};$exceptionResult=Invoke-EeeExceptionObservation $EngineState $rawException;$EngineState=$exceptionResult.state}catch{$EngineState=$null}}
try{$controlSet=New-ControlSet;$finalization=New-EeeEngineFinalizationSet $EngineState $controlSet $RecordedUtc;$plan=New-EeeEnginePublicationPlan $finalization $StagingDirectory $EvidenceDirectory;$receipts=Publish-EnginePlan $finalization $plan;$receiptValidation=Test-EeeEnginePublicationReceipts $finalization $plan $receipts;$authority=Invoke-EeeEngineFinalizationReplay $finalization $plan $receipts}
catch{
    $finalizationException=[pscustomobject][ordered]@{exception_type=$_.Exception.GetType().FullName;exception_message=$_.Exception.Message;fully_qualified_error_id=$_.FullyQualifiedErrorId;script_stack_trace=$_.ScriptStackTrace}
    Write-Utf8 (Join-Path $EvidenceDirectory 'transport/finalization-exception.txt') (($finalizationException|ConvertTo-Json -Compress)+"`n")
    throw
}
finally{foreach($needle in $SecretNeedles){[Array]::Clear($needle,0,$needle.Length)};$SecretNeedles.Clear();if(Test-Path $StagingDirectory){Remove-Item $StagingDirectory -Recurse -Force};if($MutexHeld){$Mutex.ReleaseMutex();$MutexHeld=$false};if($null-ne$Mutex){$Mutex.Dispose();$Mutex=$null}}
if(-not$receiptValidation.valid-or-not$authority.authoritative){[Console]::Error.WriteLine('authority=NON_AUTHORITATIVE failure_code=UNIFIED_ENGINE_TERMINAL_AUTHORITY_DENIED');exit 3}
Write-Output $finalization.terminal_commit.actual_completion_marker
