import assert from 'node:assert/strict';
import test from 'node:test';
import { AuthorityFailure, FOUNDATION_PINS, payloadCommitment, terminalCommitment } from './A2.5-DCA-AUTHORITY-FOUNDATION.mjs';
import { coordinateNonMutatingIntent, MUTATION_DISABLED_VERDICT } from './A2.5-DCA-RUNTIME-COORDINATOR.mjs';

const pins = { schemaVersion: FOUNDATION_PINS.schemaVersion, canonicalizationVersion: FOUNDATION_PINS.canonicalizationVersion, digestAlgorithm: 'sha256' };
const now = Date.parse('2026-08-12T00:00:00.000Z');
const buildTerminal = () => { const approvedPayload = { ...pins, payloadID: 'P1', repository: 'hqf506/AFEX', baseCommit: 'a'.repeat(64), policyClaims: {}, serverVersion: '27.5.1', expectedParticipantIDs: ['A', 'B'], threshold: 2, supportingDescription: 'review only' }; const t = { ...pins, approvedPayload, approvedPayloadDigest: payloadCommitment(approvedPayload), terminalMetadata: { policyID: 'P1', threshold: 2 }, lineageGenesisOrReference: { lineageID: 'L1' }, finalDigest: '0'.repeat(64) }; t.finalDigest = terminalCommitment(t); return t; };
const request = { actor: 'ACTOR:1', action: 'DOCKER_DESTRUCTIVE_MUTATION', target: 'CONTAINER:1', scope: ['RESOURCE:1'] };
const expectedRuntime = { repository: 'hqf506/AFEX', baseCommit: 'a'.repeat(64), daemonID: 'DAEMON:1', contextID: 'CONTEXT:1', orchestratorState: 'HEALTHY', serverVersion: '27.5.1' };
const base = () => { const terminal = buildTerminal(); const observed = { complete: true, ...expectedRuntime, observedAt: now, expiresAt: now + 60000 }; const currentEvidence = { ...pins, lineageID: 'L1', currentFinalDigest: terminal.finalDigest, currentPointerProof: {}, revocationStatus: 'CURRENT', revocationStatusProof: {}, freshnessProof: {} }; return { terminal, request, expectedRuntime, now, providers: { currentAuthority: { verify: async () => ({ verified: true, fresh: true, evidence: currentEvidence }) }, hostProvenance: { verify: async () => ({ verified: true, localBindingVerified: true, evidence: { host: 'H1' } }) }, runtimeObservation: { observe: async () => observed }, executionAuthorization: { issue: async ({ observation, currentAuthorityEvidenceDigest }) => ({ ...pins, authorizationID: 'AUTH:1', observationID: observation.observationID, actor: request.actor, exactAction: request.action, exactTarget: request.target, exactScope: request.scope, currentAuthorityEvidenceDigest, executionAuthorityProof: {}, consumptionState: 'ISSUED' }) }, durableAudit: { reserve: async () => ({ reserved: true, reservationID: 'RES:1' }), recordProposed: async () => ({ recorded: true }) } } }; };
const code = (expected) => (error) => error instanceof AuthorityFailure && error.code === expected;

test('successful validation ends at verified non-executable immutable intent', async () => { const result = await coordinateNonMutatingIntent(base()); assert.equal(result.verdict, MUTATION_DISABLED_VERDICT); assert.equal(result.mutationInvoked, false); assert.equal(result.intent.executionDisposition, 'VERIFICATION_ONLY_NON_EXECUTABLE'); assert.equal(result.intent.realMutationAuthorized, false); assert.ok(Object.isFrozen(result.intent)); });
for (const providerName of ['currentAuthority', 'hostProvenance', 'runtimeObservation', 'executionAuthorization', 'durableAudit']) test(`unavailable ${providerName} fails closed`, async () => { const input = base(); input.providers[providerName] = new Proxy({}, { get: () => async () => { throw new AuthorityFailure('PROVIDER_UNAVAILABLE', providerName); } }); await assert.rejects(coordinateNonMutatingIntent(input), code('PROVIDER_UNAVAILABLE')); });
test('stale, revoked and superseded authority fail closed', async () => { for (const [kind, expected] of [['stale', 'STALE'], ['REVOKED', 'REVOKED'], ['SUPERSEDED', 'SUPERSEDED']]) { const input = base(); const original = input.providers.currentAuthority.verify; input.providers.currentAuthority.verify = async (arg) => { const out = await original(arg); if (kind === 'stale') out.fresh = false; else out.evidence.revocationStatus = kind; return out; }; await assert.rejects(coordinateNonMutatingIntent(input), code(expected)); } });
for (const key of ['baseCommit', 'daemonID', 'contextID', 'serverVersion']) test(`changed ${key} rejects`, async () => { const input = base(); const original = input.providers.runtimeObservation.observe; input.providers.runtimeObservation.observe = async () => ({ ...await original(), [key]: 'CHANGED' }); await assert.rejects(coordinateNonMutatingIntent(input), code('CONFLICTING')); });
test('unknown orchestrator, expired and partial observation reject', async () => { for (const patch of [{ orchestratorState: 'UNKNOWN' }, { expiresAt: now }, { complete: false }]) { const input = base(); const original = input.providers.runtimeObservation.observe; input.providers.runtimeObservation.observe = async () => ({ ...await original(), ...patch }); await assert.rejects(coordinateNonMutatingIntent(input)); } });
test('over-scope and actor or target substitution reject', async () => { for (const patch of [{ exactScope: ['OTHER'] }, { actor: 'ACTOR:2' }, { exactTarget: 'OTHER' }]) { const input = base(); const original = input.providers.executionAuthorization.issue; input.providers.executionAuthorization.issue = async (arg) => ({ ...await original(arg), ...patch }); await assert.rejects(coordinateNonMutatingIntent(input), code('OVER_SCOPED')); } });
test('replay/concurrent reservation and audit failure reject', async () => { for (const patch of [{ reserve: async () => ({ reserved: false }) }, { recordProposed: async () => ({ recorded: false }) }]) { const input = base(); Object.assign(input.providers.durableAudit, patch); await assert.rejects(coordinateNonMutatingIntent(input)); } });
test('mutation callback is forbidden and cannot be invoked', async () => { const input = { ...base(), mutation: () => assert.fail('must not run') }; await assert.rejects(coordinateNonMutatingIntent(input), code('UNKNOWN')); });
