import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { EventEmitter } from 'node:events';
import { Pool } from 'pg';
import {
  AdapterFailure, FAILURE_CODES, SQLSTATE_ALLOWLIST, boundedEvidence,
  classifySqlstate, mapBoundedError, retainSqlstate, selectPrimaryFailure
} from './A2.5-PD5-REAL-DRIVER-ERROR-MAP.mjs';
import {
  COMMIT_OUTCOME, RELEASE_ACTION, ROLLBACK_STATE, TRANSACTION_STATUS,
  PoolErrorObserver, RealDriverAdapter, RollbackCoordinator,
  classifyCommitOutcome, decideRelease, mapTransactionStatus,
  observeTransactionStatus, verifySanitation
} from './A2.5-PD5-REAL-DRIVER-ADAPTER.mjs';
import {
  DeterministicScheduler, TIMEOUT_CLASSES, createDeadline, validateTimeoutPlan
} from './A2.5-PD5-REAL-DRIVER-TIMEOUTS.mjs';

class FakeClient extends EventEmitter {
  constructor(status = 'I') { super(); this.status = status; this.releases = []; this.handler = async () => ({ rows: [] }); this.releaseError = null; }
  getTransactionStatus() { return this.status; }
  query(config) { return this.handler(config); }
  release(destroy = false) { this.releases.push(destroy); if (this.releaseError) throw this.releaseError; }
}

class FakePool extends EventEmitter {
  constructor(result) { super(); this.result = result; }
  async connect() {
    if (this.result instanceof Error) throw this.result;
    return this.result;
  }
}

const controls = {
  begin: async (client) => { client.status = 'T'; },
  execute: (client, descriptor) => client.query(descriptor),
  commit: async (client) => { client.status = 'I'; },
  rollback: async (client) => { client.status = 'I'; }
};
const deferred = () => { let resolve; let reject; const promise = new Promise((a, b) => { resolve = a; reject = b; }); return { promise, resolve, reject }; };
const failure = async (promise, code) => assert.equal((await promise.then(() => null, (error) => error))?.failureCode, code);
const acquire = async (client = new FakeClient(), customControls = controls) => {
  const adapter = new RealDriverAdapter({ pool: new FakePool(client), controls: customControls });
  return { adapter, client, lease: await adapter.acquire('borrower') };
};
const healthyState = () => ({ acquired: true, owned: true, identityMatched: true, querySettlement: 'ORDINARY_SUCCESS', activeOperation: null, transactionStatus: 'IDLE', commitOutcome: 'NOT_ATTEMPTED', rollbackState: 'NOT_REQUIRED', unsafe: false, sanitationPassed: true, outstandingTimeout: false, released: false });

const tests = [];
const test = (name, run) => tests.push({ name, run });

test('01 public pg surface and checkout success', async () => { assert.equal(typeof Pool, 'function'); const { lease } = await acquire(); assert.equal(lease.snapshot().owned, true); });
test('02 pool checkout timeout', async () => { const adapter = new RealDriverAdapter({ pool: new FakePool(new Error('bounded')), controls }); await failure(adapter.acquire('borrower', { timeoutClass: 'POOL_CHECKOUT_TIMEOUT' }), 'PG_POOL_CHECKOUT_TIMEOUT'); });
test('03 pool shutdown checkout mapping', async () => { const adapter = new RealDriverAdapter({ pool: new FakePool(new AdapterFailure('PG_POOL_SHUTDOWN')), controls }); await failure(adapter.acquire('borrower'), 'PG_POOL_SHUTDOWN'); });
test('04 connection timeout mapping', () => assert.equal(mapBoundedError(new Error(), { timeoutClass: 'CONNECTION_ESTABLISHMENT_TIMEOUT' }).failureCode, 'PG_CONNECTION_TIMEOUT'));
test('05 borrower identity mismatch', async () => { const { lease } = await acquire(); await failure(lease.query('intruder', { operationId: 'OPERATION' }), 'PG_IDENTITY_MISMATCH'); assert.equal(lease.release('borrower'), RELEASE_ACTION.DESTROY_RELEASE); });
test('06 query ordinary success', async () => { const { lease } = await acquire(); assert.deepEqual(await lease.query('borrower', { operationId: 'OPERATION' }), { rows: [] }); });
test('07 query ordinary failure', async () => { const client = new FakeClient('E'); client.handler = async () => { throw new Error('bounded'); }; const { lease } = await acquire(client); await failure(lease.query('borrower', { operationId: 'OPERATION' }), 'PG_QUERY_FAILED'); assert.equal(lease.snapshot().querySettlement, 'ORDINARY_ERROR'); });
test('08 server statement timeout', () => assert.deepEqual(classifySqlstate('57014'), { failureCode: 'PG_STATEMENT_TIMEOUT', sqlstate: '57014', retryable: false }));
test('09 server lock timeout', () => assert.equal(classifySqlstate('55P03').failureCode, 'PG_LOCK_TIMEOUT'));
test('10 driver query timeout is unsafe', async () => { const { lease } = await acquire(); await failure(lease.query('borrower', { operationId: 'OPERATION', query_timeout: 1 }), 'PG_QUERY_TIMEOUT_LOCAL'); assert.equal(lease.snapshot().querySettlement, 'UNKNOWN'); });
test('11 application deadline before settlement', async () => { const d = deferred(); const client = new FakeClient('T'); client.handler = () => d.promise; const { lease } = await acquire(client); const pending = lease.query('borrower', { operationId: 'OPERATION' }); lease.expireApplicationDeadline('borrower'); d.resolve({ rows: [] }); await failure(pending, 'PG_QUERY_SETTLEMENT_UNKNOWN'); assert.equal(lease.release('borrower'), RELEASE_ACTION.DESTROY_RELEASE); });
test('12 result before application deadline', async () => { const { lease } = await acquire(); await lease.query('borrower', { operationId: 'OPERATION' }); lease.expireApplicationDeadline('borrower'); assert.equal(lease.snapshot().querySettlement, 'ORDINARY_SUCCESS'); });
test('13 deterministic timeout ordering', () => { const s = new DeterministicScheduler(); const seen = []; s.schedule(2, () => seen.push(2)); s.schedule(1, () => seen.push(1)); s.advanceTo(2); assert.deepEqual(seen, [1, 2]); });
test('14 deadline disarm', () => { const s = new DeterministicScheduler(); let fired = false; const d = createDeadline(s, 1, () => { fired = true; }); assert.equal(d.disarm(), true); s.advanceTo(1); assert.equal(fired, false); });
test('15 timeout plan validation', () => { const plan = { checkoutMs: 2, connectionMs: 2, lockMs: 1, statementMs: 2, applicationMs: 3, settlementMs: 1, rollbackMs: 1, destroyMs: 1, overallMs: 4 }; assert.equal(validateTimeoutPlan(plan).valid, true); assert.equal(TIMEOUT_CLASSES.length, 11); });
test('16 transaction status observation', () => { assert.deepEqual(['I', 'T', 'E', 'x'].map(mapTransactionStatus), ['IDLE', 'IN_TRANSACTION', 'FAILED_TRANSACTION', 'UNKNOWN']); });
test('17 missing transaction status method', () => assert.equal(observeTransactionStatus({}), TRANSACTION_STATUS.UNKNOWN));
test('18 mismatched transaction status', () => assert.equal(observeTransactionStatus({ getTransactionStatus: () => 'T' }, TRANSACTION_STATUS.IDLE), TRANSACTION_STATUS.UNKNOWN));
test('19 rollback success exactly once', async () => { const r = new RollbackCoordinator(); r.require(); assert.equal(await r.attempt({ ordinarilySettled: true, run: async () => {}, observeStatus: () => 'IDLE' }), ROLLBACK_STATE.SUCCEEDED); assert.equal(r.attempts, 1); });
test('20 rollback failure', async () => { const r = new RollbackCoordinator(); r.require(); assert.equal(await r.attempt({ ordinarilySettled: true, run: async () => { throw new Error(); }, observeStatus: () => 'IDLE' }), ROLLBACK_STATE.FAILED); });
test('21 rollback timeout', async () => { const r = new RollbackCoordinator(); r.require(); assert.equal(await r.attempt({ ordinarilySettled: true, timedOut: true, run: async () => {}, observeStatus: () => 'IDLE' }), ROLLBACK_STATE.TIMED_OUT); assert.equal(r.commandOutcome, 'TIMED_OUT'); });
test('22 duplicate rollback rejected', async () => { const r = new RollbackCoordinator(); await r.attempt({ ordinarilySettled: true, run: async () => {}, observeStatus: () => 'IDLE' }); await failure(r.attempt({ ordinarilySettled: true, run: async () => {}, observeStatus: () => 'IDLE' }), 'PG_RELEASE_STATE_INVALID'); });
test('23 commit success', async () => { const { lease } = await acquire(new FakeClient('T')); assert.equal(await lease.commit('borrower'), COMMIT_OUTCOME.KNOWN_COMMITTED); });
test('24 commit known not committed', () => assert.equal(classifyCommitOutcome({ rejected: true, ordinarilySettled: true, unsafe: false, transactionStatus: 'IN_TRANSACTION' }), COMMIT_OUTCOME.KNOWN_NOT_COMMITTED));
test('25 commit ambiguity', () => assert.equal(classifyCommitOutcome({ rejected: true, ordinarilySettled: false, unsafe: false, transactionStatus: 'UNKNOWN' }), COMMIT_OUTCOME.AMBIGUOUS));
test('26 socket error while owned', async () => { const d = deferred(); const client = new FakeClient('T'); client.handler = () => d.promise; const { lease } = await acquire(client); const pending = lease.query('borrower', { operationId: 'OPERATION' }); client.emit('end'); d.reject(new Error('bounded')); await failure(pending, 'PG_SOCKET_ERROR'); });
test('27 protocol error while owned', async () => { const { client, lease } = await acquire(); client.emit('error', Object.assign(new Error('bounded'), { code: '08P01' })); assert.equal(lease.snapshot().unsafeCode, 'PG_PROTOCOL_ERROR'); });
test('28 client error while owned', async () => { const { client, lease } = await acquire(); client.emit('error', new Error('bounded')); assert.equal(lease.snapshot().unsafeCode, 'PG_CLIENT_ERROR'); });
test('29 idle pool error is observed', () => { const pool = new FakePool(null); const observer = new PoolErrorObserver(pool); pool.emit('error', Object.assign(new Error('bounded'), { code: '08006' })); assert.equal(observer.snapshot()[0].failureCode, 'PG_POOL_ERROR'); });
test('30 sanitation pass and fail', () => { assert.equal(verifySanitation({ ...healthyState(), forbiddenSessionMutation: false }).passed, true); assert.equal(verifySanitation({ ...healthyState(), unsafe: true, forbiddenSessionMutation: false }).failureCode, 'PG_SANITATION_FAILED'); });
test('31 normal release', async () => { const { client, lease } = await acquire(); await lease.query('borrower', { operationId: 'OPERATION' }); assert.equal(lease.sanitize('borrower').passed, true); assert.equal(lease.release('borrower'), RELEASE_ACTION.NORMAL_RELEASE); assert.deepEqual(client.releases, [false]); });
test('32 destructive release and exactly once', async () => { const { client, lease } = await acquire(); assert.equal(lease.release('borrower'), RELEASE_ACTION.DESTROY_RELEASE); assert.deepEqual(client.releases, [true]); assert.throws(() => lease.release('borrower'), (e) => e.failureCode === 'PG_RELEASE_STATE_INVALID'); assert.deepEqual(client.releases, [true]); });
test('33 use after destroy and post-release end isolation', async () => { const { client, lease } = await acquire(); lease.release('borrower'); const before = lease.snapshot(); client.emit('end'); assert.deepEqual(lease.snapshot(), before); await failure(lease.query('borrower', { operationId: 'OPERATION' }), 'PG_RELEASE_STATE_INVALID'); });
test('34 raw text named statements and mutation metadata rejected', async () => { for (const descriptor of [{ text: 'ARBITRARY' }, { operationId: 'OPERATION', name: 'forbidden' }, { operationId: 'OPERATION', sessionMutation: false }]) { const { lease } = await acquire(); await failure(lease.query('borrower', descriptor), 'PG_RELEASE_STATE_INVALID'); } });
test('35 bounded SQLSTATE and no business retry', () => { assert.equal(retainSqlstate('SECRET'), null); for (const code of SQLSTATE_ALLOWLIST) assert.equal(retainSqlstate(code), code); assert.equal(classifySqlstate('40001').retryable, false); assert.equal(classifySqlstate('40P01').retryable, false); assert.equal(new AdapterFailure('PG_QUERY_FAILED').retryable, false); });
test('36 frozen failure vocabulary, precedence, and bounded evidence', () => { assert.equal(FAILURE_CODES.length, 23); for (const code of FAILURE_CODES) assert.equal(boundedEvidence(code, { stage: 'test', sqlstate: 'SECRET' }).failureCode, code); assert.equal(selectPrimaryFailure('PG_QUERY_FAILED', 'PG_COMMIT_OUTCOME_UNKNOWN'), 'PG_COMMIT_OUTCOME_UNKNOWN'); assert.equal(decideRelease(healthyState()), RELEASE_ACTION.NORMAL_RELEASE); });
test('37 throwing transaction status is unknown and destroys', async () => { const client = new FakeClient(); client.getTransactionStatus = () => { throw new Error('not retained'); }; const { lease } = await acquire(client); assert.equal(lease.snapshot().transactionStatus, TRANSACTION_STATUS.UNKNOWN); assert.equal(lease.release('borrower'), RELEASE_ACTION.DESTROY_RELEASE); assert.equal(JSON.stringify(lease.snapshot()).includes('not retained'), false); });
test('38 normal release exception terminalizes every public operation', async () => { const { client, lease } = await acquire(); await lease.query('borrower', { operationId: 'OPERATION' }); lease.sanitize('borrower'); client.releaseError = new Error('not retained'); assert.throws(() => lease.release('borrower'), (e) => e.failureCode === 'PG_RELEASE_STATE_INVALID'); assert.equal(lease.snapshot().owned, false); assert.equal(lease.snapshot().released, true); assert.equal(lease.snapshot().releaseFailureCode, 'PG_RELEASE_STATE_INVALID'); for (const operation of [lease.query('borrower', { operationId: 'OPERATION' }), lease.commit('borrower'), lease.rollback('borrower')]) await failure(operation, 'PG_RELEASE_STATE_INVALID'); assert.throws(() => lease.release('borrower'), (e) => e.failureCode === 'PG_RELEASE_STATE_INVALID'); assert.deepEqual(client.releases, [false]); assert.equal(JSON.stringify(lease.snapshot()).includes('not retained'), false); });
test('39 destroy release exception terminalizes every public operation', async () => { const { client, lease } = await acquire(); client.releaseError = new Error('not retained'); assert.throws(() => lease.release('borrower'), (e) => e.failureCode === 'PG_CLIENT_DESTROY_REQUIRED'); assert.equal(lease.snapshot().owned, false); assert.equal(lease.snapshot().released, true); assert.equal(lease.snapshot().releaseFailureCode, 'PG_CLIENT_DESTROY_REQUIRED'); for (const operation of [lease.query('borrower', { operationId: 'OPERATION' }), lease.commit('borrower'), lease.rollback('borrower')]) await failure(operation, 'PG_RELEASE_STATE_INVALID'); assert.throws(() => lease.release('borrower'), (e) => e.failureCode === 'PG_RELEASE_STATE_INVALID'); assert.deepEqual(client.releases, [true]); assert.equal(JSON.stringify(lease.snapshot()).includes('not retained'), false); });
test('40 commit success before deadline stays known', async () => { const { lease } = await acquire(new FakeClient('T')); assert.equal(await lease.commit('borrower'), COMMIT_OUTCOME.KNOWN_COMMITTED); lease.expireApplicationDeadline('borrower'); assert.equal(lease.snapshot().commitOutcome, COMMIT_OUTCOME.KNOWN_COMMITTED); });
test('41 application deadline makes pending commit ambiguous', async () => { const d = deferred(); const custom = { ...controls, commit: () => d.promise }; const { lease } = await acquire(new FakeClient('T'), custom); const pending = lease.commit('borrower'); lease.expireApplicationDeadline('borrower'); await failure(pending, 'PG_COMMIT_OUTCOME_UNKNOWN'); d.resolve(); await Promise.resolve(); assert.equal(lease.snapshot().commitOutcome, COMMIT_OUTCOME.AMBIGUOUS); assert.equal(lease.release('borrower'), RELEASE_ACTION.DESTROY_RELEASE); });
test('42 overall timeout makes pending commit ambiguous', async () => { const d = deferred(); const custom = { ...controls, commit: () => d.promise }; const { lease } = await acquire(new FakeClient('T'), custom); const pending = lease.commit('borrower'); lease.expireOverallOperation('borrower'); await failure(pending, 'PG_COMMIT_OUTCOME_UNKNOWN'); d.resolve(); await Promise.resolve(); assert.equal(lease.snapshot().commitOutcome, COMMIT_OUTCOME.AMBIGUOUS); });
test('43 late commit rejection cannot trigger rollback or retry', async () => { const d = deferred(); let rollbacks = 0; const custom = { ...controls, commit: () => d.promise, rollback: async () => { rollbacks += 1; } }; const { lease } = await acquire(new FakeClient('T'), custom); const pending = lease.commit('borrower'); lease.expireApplicationDeadline('borrower'); await failure(pending, 'PG_COMMIT_OUTCOME_UNKNOWN'); d.reject(new Error('not retained')); await Promise.resolve(); assert.equal(rollbacks, 0); await failure(lease.commit('borrower'), 'PG_RELEASE_STATE_INVALID'); });
test('44 query during query is rejected', async () => { const d = deferred(); const client = new FakeClient(); client.handler = () => d.promise; const { lease } = await acquire(client); const pending = lease.query('borrower', { operationId: 'OPERATION' }); await failure(lease.query('borrower', { operationId: 'OPERATION' }), 'PG_RELEASE_STATE_INVALID'); d.resolve({ rows: [] }); await pending; });
test('45 query during commit is rejected', async () => { const d = deferred(); const { lease } = await acquire(new FakeClient('T'), { ...controls, commit: () => d.promise }); const pending = lease.commit('borrower'); await failure(lease.query('borrower', { operationId: 'OPERATION' }), 'PG_RELEASE_STATE_INVALID'); lease.expireApplicationDeadline('borrower'); await failure(pending, 'PG_COMMIT_OUTCOME_UNKNOWN'); d.resolve(); });
test('46 commit during query is rejected', async () => { const d = deferred(); const client = new FakeClient(); client.handler = () => d.promise; const { lease } = await acquire(client); const pending = lease.query('borrower', { operationId: 'OPERATION' }); await failure(lease.commit('borrower'), 'PG_RELEASE_STATE_INVALID'); d.resolve({ rows: [] }); await pending; });
test('47 rollback during query is rejected', async () => { const d = deferred(); const client = new FakeClient(); client.handler = () => d.promise; const { lease } = await acquire(client); const pending = lease.query('borrower', { operationId: 'OPERATION' }); await failure(lease.rollback('borrower'), 'PG_RELEASE_STATE_INVALID'); d.resolve({ rows: [] }); await pending; });
test('48 rollback during commit is rejected', async () => { const d = deferred(); const { lease } = await acquire(new FakeClient('T'), { ...controls, commit: () => d.promise }); const pending = lease.commit('borrower'); await failure(lease.rollback('borrower'), 'PG_RELEASE_STATE_INVALID'); lease.expireApplicationDeadline('borrower'); await failure(pending, 'PG_COMMIT_OUTCOME_UNKNOWN'); d.resolve(); });
test('49 duplicate commit is rejected', async () => { const { lease } = await acquire(new FakeClient('T')); await lease.commit('borrower'); await failure(lease.commit('borrower'), 'PG_RELEASE_STATE_INVALID'); });
test('50 sanitation during active query is rejected', async () => { const d = deferred(); const client = new FakeClient(); client.handler = () => d.promise; const { lease } = await acquire(client); const pending = lease.query('borrower', { operationId: 'OPERATION' }); assert.throws(() => lease.sanitize('borrower'), (e) => e.failureCode === 'PG_RELEASE_STATE_INVALID'); d.resolve({ rows: [] }); await pending; });
test('51 release during unresolved query is rejected', async () => { const d = deferred(); const client = new FakeClient(); client.handler = () => d.promise; const { lease } = await acquire(client); const pending = lease.query('borrower', { operationId: 'OPERATION' }); assert.throws(() => lease.release('borrower'), (e) => e.failureCode === 'PG_RELEASE_STATE_INVALID'); assert.deepEqual(client.releases, []); d.resolve({ rows: [] }); await pending; });
test('52 normal post-release error belongs to pool authority', async () => { const { client, lease } = await acquire(); client.on('error', () => {}); await lease.query('borrower', { operationId: 'OPERATION' }); lease.sanitize('borrower'); lease.release('borrower'); const before = lease.snapshot(); client.emit('error', new Error('pool-owned')); assert.deepEqual(lease.snapshot(), before); await failure(lease.query('borrower', { operationId: 'OPERATION' }), 'PG_RELEASE_STATE_INVALID'); assert.throws(() => lease.release('borrower')); });
test('53 trusted operation descriptor excludes raw text', async () => { let observed; const custom = { ...controls, execute: async (_client, descriptor) => { observed = descriptor; return { rows: [] }; } }; const { lease } = await acquire(new FakeClient(), custom); await lease.query('borrower', { operationId: 'READ_MODEL', values: [1] }); assert.deepEqual(observed, { operationId: 'READ_MODEL', values: [1] }); assert.equal(Object.hasOwn(observed, 'text'), false); });
test('54 query failure then rollback failure precedence', async () => { const client = new FakeClient('E'); client.handler = async () => { throw new Error('not retained'); }; const custom = { ...controls, rollback: async () => { throw new Error('not retained'); } }; const { lease } = await acquire(client, custom); await failure(lease.query('borrower', { operationId: 'OPERATION' }), 'PG_QUERY_FAILED'); await failure(lease.rollback('borrower'), 'PG_ROLLBACK_FAILED'); assert.equal(lease.snapshot().rollbackCommandOutcome, 'FAILED'); assert.equal(lease.snapshot().unsafeCode, 'PG_ROLLBACK_FAILED'); assert.equal(lease.release('borrower'), RELEASE_ACTION.DESTROY_RELEASE); });
test('55 statement timeout then unknown status precedence', async () => { const client = new FakeClient('invalid'); client.handler = async () => { throw Object.assign(new Error('not retained'), { code: '57014' }); }; const { lease } = await acquire(client); await failure(lease.query('borrower', { operationId: 'OPERATION' }), 'PG_TRANSACTION_STATUS_UNKNOWN'); assert.equal(lease.snapshot().unsafeCode, 'PG_TRANSACTION_STATUS_UNKNOWN'); assert.equal(lease.release('borrower'), RELEASE_ACTION.DESTROY_RELEASE); });
test('56 query failure then socket escalation precedence', async () => { const client = new FakeClient('E'); client.handler = async () => { throw new Error('not retained'); }; const { lease } = await acquire(client); await failure(lease.query('borrower', { operationId: 'OPERATION' }), 'PG_QUERY_FAILED'); client.emit('end'); assert.equal(lease.snapshot().unsafeCode, 'PG_SOCKET_ERROR'); assert.equal(lease.release('borrower'), RELEASE_ACTION.DESTROY_RELEASE); });
test('57 query failure rollback recovery then sanitation failure precedence', async () => { const client = new FakeClient('E'); client.handler = async () => { throw new Error('not retained'); }; const { lease } = await acquire(client); await failure(lease.query('borrower', { operationId: 'OPERATION' }), 'PG_QUERY_FAILED'); assert.equal(await lease.rollback('borrower'), ROLLBACK_STATE.SUCCEEDED); client.status = 'T'; assert.equal(lease.sanitize('borrower').failureCode, 'PG_SANITATION_FAILED'); assert.equal(lease.snapshot().unsafeCode, 'PG_SANITATION_FAILED'); assert.equal(lease.release('borrower'), RELEASE_ACTION.DESTROY_RELEASE); });
test('58 ambiguous commit survives later client failure precedence', async () => { const d = deferred(); let rollbacks = 0; const custom = { ...controls, commit: () => d.promise, rollback: async () => { rollbacks += 1; } }; const { client, lease } = await acquire(new FakeClient('T'), custom); const pending = lease.commit('borrower'); lease.expireApplicationDeadline('borrower'); await failure(pending, 'PG_COMMIT_OUTCOME_UNKNOWN'); client.emit('error', new Error('not retained')); d.resolve(); await Promise.resolve(); assert.equal(lease.snapshot().commitOutcome, COMMIT_OUTCOME.AMBIGUOUS); assert.equal(lease.snapshot().unsafeCode, 'PG_COMMIT_OUTCOME_UNKNOWN'); assert.equal(rollbacks, 0); assert.equal(lease.release('borrower'), RELEASE_ACTION.DESTROY_RELEASE); });
test('59 rollback succeeds with missing status method exactly once then destroys', async () => { let rollbacks = 0; const client = new FakeClient('E'); client.handler = async () => { throw new Error('bounded'); }; const custom = { ...controls, rollback: async (target) => { rollbacks += 1; target.status = 'I'; } }; const { lease } = await acquire(client, custom); await failure(lease.query('borrower', { operationId: 'OPERATION' }), 'PG_QUERY_FAILED'); client.getTransactionStatus = undefined; await failure(lease.rollback('borrower'), 'PG_TRANSACTION_STATUS_UNKNOWN'); assert.equal(lease.snapshot().rollbackCommandOutcome, 'SUCCEEDED'); assert.equal(lease.snapshot().rollbackObservedTransactionStatus, TRANSACTION_STATUS.UNKNOWN); assert.equal(rollbacks, 1); await failure(lease.rollback('borrower'), 'PG_RELEASE_STATE_INVALID'); assert.equal(rollbacks, 1); assert.equal(lease.release('borrower'), RELEASE_ACTION.DESTROY_RELEASE); });
test('60 rollback succeeds with invalid status exactly once then destroys', async () => { let rollbacks = 0; const client = new FakeClient('E'); client.handler = async () => { throw new Error('bounded'); }; const custom = { ...controls, rollback: async (target) => { rollbacks += 1; target.status = 'invalid'; } }; const { lease } = await acquire(client, custom); await failure(lease.query('borrower', { operationId: 'OPERATION' }), 'PG_QUERY_FAILED'); await failure(lease.rollback('borrower'), 'PG_TRANSACTION_STATUS_UNKNOWN'); assert.equal(lease.snapshot().rollbackCommandOutcome, 'SUCCEEDED'); assert.equal(lease.snapshot().rollbackObservedTransactionStatus, TRANSACTION_STATUS.UNKNOWN); assert.equal(rollbacks, 1); await failure(lease.rollback('borrower'), 'PG_RELEASE_STATE_INVALID'); assert.equal(rollbacks, 1); assert.equal(lease.release('borrower'), RELEASE_ACTION.DESTROY_RELEASE); });
test('61 rollback succeeds with throwing status exactly once then destroys', async () => { let rollbacks = 0; const client = new FakeClient('E'); client.handler = async () => { throw new Error('bounded'); }; const custom = { ...controls, rollback: async (target) => { rollbacks += 1; target.getTransactionStatus = () => { throw new Error('not retained'); }; } }; const { lease } = await acquire(client, custom); await failure(lease.query('borrower', { operationId: 'OPERATION' }), 'PG_QUERY_FAILED'); await failure(lease.rollback('borrower'), 'PG_TRANSACTION_STATUS_UNKNOWN'); assert.equal(lease.snapshot().rollbackObservedTransactionStatus, TRANSACTION_STATUS.UNKNOWN); assert.equal(rollbacks, 1); await failure(lease.rollback('borrower'), 'PG_RELEASE_STATE_INVALID'); assert.equal(rollbacks, 1); assert.equal(JSON.stringify(lease.snapshot()).includes('not retained'), false); assert.equal(lease.release('borrower'), RELEASE_ACTION.DESTROY_RELEASE); });
test('62 rollback succeeds with idle status and may release normally', async () => { const client = new FakeClient('E'); client.handler = async () => { throw new Error('bounded'); }; const { lease } = await acquire(client); await failure(lease.query('borrower', { operationId: 'OPERATION' }), 'PG_QUERY_FAILED'); assert.equal(await lease.rollback('borrower'), ROLLBACK_STATE.SUCCEEDED); assert.equal(lease.snapshot().rollbackObservedTransactionStatus, TRANSACTION_STATUS.IDLE); assert.equal(lease.sanitize('borrower').passed, true); assert.equal(lease.release('borrower'), RELEASE_ACTION.NORMAL_RELEASE); });
test('63 rollback succeeds but remains in transaction and destroys', async () => { const client = new FakeClient('E'); client.handler = async () => { throw new Error('bounded'); }; const custom = { ...controls, rollback: async (target) => { target.status = 'T'; } }; const { lease } = await acquire(client, custom); await failure(lease.query('borrower', { operationId: 'OPERATION' }), 'PG_QUERY_FAILED'); await failure(lease.rollback('borrower'), 'PG_ROLLBACK_FAILED'); assert.equal(lease.snapshot().rollbackObservedTransactionStatus, TRANSACTION_STATUS.IN_TRANSACTION); assert.equal(lease.release('borrower'), RELEASE_ACTION.DESTROY_RELEASE); });
test('64 rollback succeeds but remains failed transaction and destroys', async () => { const client = new FakeClient('E'); client.handler = async () => { throw new Error('bounded'); }; const custom = { ...controls, rollback: async (target) => { target.status = 'E'; } }; const { lease } = await acquire(client, custom); await failure(lease.query('borrower', { operationId: 'OPERATION' }), 'PG_QUERY_FAILED'); await failure(lease.rollback('borrower'), 'PG_ROLLBACK_FAILED'); assert.equal(lease.snapshot().rollbackObservedTransactionStatus, TRANSACTION_STATUS.FAILED_TRANSACTION); assert.equal(lease.release('borrower'), RELEASE_ACTION.DESTROY_RELEASE); });
test('65 statement timeout then rollback unknown status precedence', async () => { const client = new FakeClient('E'); client.handler = async () => { throw Object.assign(new Error('bounded'), { code: '57014' }); }; const custom = { ...controls, rollback: async (target) => { target.status = 'invalid'; } }; const { lease } = await acquire(client, custom); await failure(lease.query('borrower', { operationId: 'OPERATION' }), 'PG_STATEMENT_TIMEOUT'); await failure(lease.rollback('borrower'), 'PG_TRANSACTION_STATUS_UNKNOWN'); assert.equal(lease.snapshot().unsafeCode, 'PG_TRANSACTION_STATUS_UNKNOWN'); assert.equal(lease.release('borrower'), RELEASE_ACTION.DESTROY_RELEASE); });
test('66 sanitation fresh unknown missing invalid and throwing observations destroy', async () => { const cases = [{ name: 'missing', apply: (client) => { client.getTransactionStatus = undefined; } }, { name: 'invalid', apply: (client) => { client.status = 'invalid'; } }, { name: 'throwing', apply: (client) => { client.getTransactionStatus = () => { throw new Error('not retained'); }; } }]; for (const entry of cases) { const { client, lease } = await acquire(); await lease.query('borrower', { operationId: 'OPERATION' }); assert.equal(lease.snapshot().transactionStatus, TRANSACTION_STATUS.IDLE, entry.name); entry.apply(client); const sanitation = lease.sanitize('borrower'); assert.equal(sanitation.passed, false, entry.name); assert.equal(lease.snapshot().transactionStatus, TRANSACTION_STATUS.UNKNOWN, entry.name); client.getTransactionStatus = () => 'I'; assert.equal(lease.sanitize('borrower').passed, false, entry.name); assert.equal(JSON.stringify(lease.snapshot()).includes('not retained'), false, entry.name); assert.equal(lease.release('borrower'), RELEASE_ACTION.DESTROY_RELEASE, entry.name); } });

const results = [];
for (const entry of tests) {
  try { await entry.run(); results.push({ name: entry.name, status: 'PASS' }); }
  catch (error) { results.push({ name: entry.name, status: 'FAIL', error: error?.message ?? String(error) }); }
}
const digest = createHash('sha256').update(JSON.stringify(results)).digest('hex');
for (const result of results) console.log(`${result.status} ${result.name}${result.error ? ` :: ${result.error}` : ''}`);
console.log(`TEST_COUNT ${results.length}`);
console.log(`RESULT_DIGEST ${digest}`);
if (results.some((result) => result.status === 'FAIL')) {
  console.log('A25PD5_TESTS_FAILURE');
  process.exitCode = 1;
} else {
  console.log('A25PD5_TESTS_SUCCESS');
}
