import assert from 'node:assert/strict';
import test from 'node:test';
import { AuthorityFailure } from './A2.5-DCA-AUTHORITY-FOUNDATION.mjs';
import { GENERIC_EXECUTOR_STATUS, OPERATION_CATALOG, OPERATION_DISABLED_VERDICT, buildDisabledOperationProtocol, classifyInterruptedOperation, rejectGenericExecutor, verifyOperationPostcondition, verifyOperationPrecondition } from './A2.5-DCA-O10A-OPERATION-PROTOCOLS.mjs';

const code = (expected) => (error) => error instanceof AuthorityFailure && error.code === expected;
const candidate = OPERATION_CATALOG.find((x) => x.disposition === 'VERIFICATION_ONLY_INTENT_TEMPLATE');
const input = () => ({ operationID: candidate.operationID, actor: 'ACTOR:1', action: candidate.exactDockerAction, target: 'sha256:immutable-target', scope: ['RESOURCE:1'], immutableTargetIdentity: { id: 'sha256:immutable-target', type: candidate.targetType }, runtimeIdentity: { host: 'HOST:1', daemon: 'DAEMON:1', context: 'CONTEXT:1' }, repositoryBase: '3c90ca74758f0511c2bdc10009bf15d618de39e8', requiredPreState: { state: 'RUNNING', generation: 1 }, desiredPostState: { state: 'STOPPED', generation: 1 }, authorizationID: 'AUTH:1', durableIntentID: 'INTENT:1', currentAuthorityDigest: 'a'.repeat(64), trustedTimeDigest: 'b'.repeat(64) });

test('catalog has exact verification-only classification for every inventoried operation', () => { assert.equal(OPERATION_CATALOG.length, 10); assert.deepEqual(Object.fromEntries(['READ_ONLY', 'VERIFICATION_ONLY_INTENT_TEMPLATE', 'PROHIBITED'].map((d) => [d, OPERATION_CATALOG.filter((x) => x.disposition === d).length])), { READ_ONLY: 1, VERIFICATION_ONLY_INTENT_TEMPLATE: 4, PROHIBITED: 5 }); for (const operation of OPERATION_CATALOG) assert.ok(operation.operationID && operation.exactDockerAction && operation.targetType && operation.idempotency && operation.crashAmbiguity); });
for (const operation of OPERATION_CATALOG.filter((x) => x.disposition === 'VERIFICATION_ONLY_INTENT_TEMPLATE')) test(`${operation.operationID} remains non-executable`, () => { const value = buildDisabledOperationProtocol({ ...input(), operationID: operation.operationID, action: operation.exactDockerAction, immutableTargetIdentity: { id: 'ID:1', type: operation.targetType } }); assert.equal(value.decisionPoint, OPERATION_DISABLED_VERDICT); assert.equal(value.executionDisposition, 'VERIFICATION_ONLY_NON_EXECUTABLE'); assert.equal(value.realMutationAuthorized, false); assert.equal(value.mutationInvoked, false); assert.equal(value.replayAllowed, false); });
test('precondition and postcondition mismatches fail closed', () => { const protocol = buildDisabledOperationProtocol(input()); assert.throws(() => verifyOperationPrecondition(protocol, { state: 'OTHER' }), code('CONFLICTING')); assert.throws(() => verifyOperationPostcondition(protocol, { state: 'OTHER' }), code('UNVERIFIABLE_EVIDENCE')); });
test('target, daemon/context/host, base, lineage/time and authorization are digest-bound', () => { const original = buildDisabledOperationProtocol(input()); for (const mutate of [v => { v.target = 'OTHER'; }, v => { v.runtimeIdentity.daemon = 'OTHER'; }, v => { v.runtimeIdentity.context = 'OTHER'; }, v => { v.runtimeIdentity.host = 'OTHER'; }, v => { v.repositoryBase = 'OTHER'; }, v => { v.currentAuthorityDigest = 'c'.repeat(64); }, v => { v.trustedTimeDigest = 'c'.repeat(64); }, v => { v.authorizationID = 'AUTH:2'; }]) { const changed = structuredClone(input()); mutate(changed); assert.notEqual(buildDisabledOperationProtocol(changed).intentDigest, original.intentDigest); } });
test('duplicate durable intent and authorization replay must be rejected by provider', () => { const protocol = buildDisabledOperationProtocol(input()); assert.equal(protocol.replayAllowed, false); assert.equal(protocol.recoveryRequiresNewAuthorization, true); });
test('crash before mutation, crash after request and lost response prohibit blind retry', () => { assert.deepEqual(classifyInterruptedOperation('BEFORE_MUTATION'), { state: 'CANCELLED', replayAllowed: false, recoveryRequiresNewAuthorization: true }); for (const stage of ['AFTER_REQUEST', 'LOST_RESPONSE']) assert.deepEqual(classifyInterruptedOperation(stage), { state: 'UNKNOWN', replayAllowed: false, recoveryRequiresNewAuthorization: true }); });
test('generic executor is prohibited', () => { assert.equal(GENERIC_EXECUTOR_STATUS, 'PROHIBITED'); assert.throws(() => rejectGenericExecutor(), code('UNSUPPORTED')); });
test('mutation callback cannot be supplied', () => assert.throws(() => buildDisabledOperationProtocol({ ...input(), mutation: () => assert.fail('never') }), code('UNKNOWN')));
