import 'server-only'

export const CORE_V2_CREDENTIAL_BOUNDARIES = Object.freeze({
  browser_supabase: {
    creation: ['browser_client_factory'],
    imports: ['client_components', 'browser_hooks'],
    credentialSource: 'public_anon_configuration',
    operations: ['user_scoped_rls_reads'],
    forbidden: ['service_role', 'core_v2_tables', 'p2d20', 'executor', 'replay'],
    browserReachable: true,
    databaseRoleIntent: 'anon_or_authenticated',
    directTableWrites: false,
    acquisition: false,
    execution: false,
    replay: false,
  },
  user_scoped_server: {
    creation: ['server_request_scope'],
    imports: ['route_handlers', 'server_actions', 'server_components'],
    credentialSource: 'verified_user_session',
    operations: ['user_scoped_rls_reads'],
    forbidden: ['service_role_default', 'core_v2_table_writes'],
    browserReachable: false,
    databaseRoleIntent: 'authenticated',
    directTableWrites: false,
    acquisition: false,
    execution: false,
    replay: false,
  },
  trusted_service_role: {
    creation: ['approved_server_only_factory'],
    imports: ['explicit_legacy_admin_or_provider_modules'],
    credentialSource: 'server_secret_store',
    operations: ['explicit_reviewed_legacy_operations'],
    forbidden: ['browser', 'default_core_v2_runtime', 'direct_core_v2_ledgers'],
    browserReachable: false,
    databaseRoleIntent: 'service_role',
    directTableWrites: false,
    acquisition: false,
    execution: false,
    replay: false,
  },
  core_v2_executor: {
    creation: ['future_reviewed_server_adapter'],
    imports: ['future_core_v2_runtime_only'],
    credentialSource: 'dedicated_managed_login',
    operations: ['p2d20_acquisition', 'future_reviewed_executor_rpc'],
    forbidden: ['browser', 'service_role', 'direct_ledger_writes'],
    browserReachable: false,
    databaseRoleIntent: 'afex_core_runtime_via_explicit_set_role',
    directTableWrites: false,
    acquisition: true,
    execution: true,
    replay: true,
  },
  worker: {
    creation: ['future_reviewed_worker_adapter'],
    imports: ['future_background_worker_only'],
    credentialSource: 'dedicated_managed_login',
    operations: ['future_outbox_claim_and_result_rpc'],
    forbidden: ['browser', 'order_mutation', 'p2d20', 'executor'],
    browserReachable: false,
    databaseRoleIntent: 'dedicated_outbox_worker_via_explicit_set_role',
    directTableWrites: false,
    acquisition: false,
    execution: false,
    replay: false,
  },
} as const)
