'use client'
import { useCallback, useEffect, useId, useRef, useState } from 'react'
import { usePathname, useRouter } from 'next/navigation'
import type { DeveloperSupportNotification, DeveloperSupportNotificationResponse } from '@/lib/support/contracts'
export function DeveloperSupportNotifications() {
 const pathname = usePathname(); const router = useRouter(); const panelId = useId(); const bellRef = useRef<HTMLButtonElement|null>(null); const panelRef = useRef<HTMLDivElement|null>(null); const requestRef = useRef<AbortController|null>(null)
 const [open,setOpen]=useState(false); const [items,setItems]=useState<DeveloperSupportNotification[]>([]); const [unreadCount,setUnreadCount]=useState(0); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [markingAll,setMarkingAll]=useState(false); const [openingKey,setOpeningKey]=useState('')
 const load=useCallback(async(background=false)=>{if(requestRef.current)return;const controller=new AbortController();requestRef.current=controller;if(!background)setLoading(true);try{const response=await fetch('/api/provider/support/notifications',{signal:controller.signal,cache:'no-store'});const result=await response.json() as DeveloperSupportNotificationResponse&{success?:boolean;error?:string};if(!response.ok||!result.success)throw new Error(result.error||'تعذر تحميل إشعارات الدعم.');setItems(result.items);setUnreadCount(result.unreadCount);setError('')}catch(caught){if(!controller.signal.aborted)setError(caught instanceof Error?caught.message:'تعذر تحميل إشعارات الدعم.')}finally{if(requestRef.current===controller)requestRef.current=null;if(!background)setLoading(false)}},[])
 useEffect(()=>{const initial=window.setTimeout(()=>void load(),0);const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void load(true)},60_000);const visible=()=>{if(document.visibilityState==='visible')void load(true)};document.addEventListener('visibilitychange',visible);return()=>{window.clearTimeout(initial);window.clearInterval(timer);document.removeEventListener('visibilitychange',visible);requestRef.current?.abort()}},[load])
 useEffect(()=>{if(!open)return;const close=(event:MouseEvent)=>{const target=event.target as Node;if(!panelRef.current?.contains(target)&&!bellRef.current?.contains(target))setOpen(false)};const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'){setOpen(false);bellRef.current?.focus()}};document.addEventListener('mousedown',close);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('mousedown',close);document.removeEventListener('keydown',escape)}},[open])
 const openNotification=async(item:DeveloperSupportNotification)=>{if(openingKey)return;setOpeningKey(item.event_key);if(item.unread){const response=await fetch('/api/provider/support/notifications/read',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventType:item.event_type,eventId:item.event_id})});if(response.ok){setItems(current=>current.map(entry=>entry.event_key===item.event_key?{...entry,unread:false}:entry));setUnreadCount(value=>Math.max(0,value-1))}else setError('تعذر تحديث حالة الإشعار، ويمكنك متابعة فتح التذكرة.')}setOpen(false);if(pathname==='/developer/support'){const next=new URL(window.location.href);next.searchParams.set('ticket',item.ticket_id);window.history.pushState({...window.history.state,providerTicketDrawer:true},'',next);window.dispatchEvent(new CustomEvent('provider-support:open-ticket',{detail:{ticketId:item.ticket_id}}))}else router.push(`/developer/support?ticket=${encodeURIComponent(item.ticket_id)}`);setOpeningKey('')}
 const markAll=async()=>{if(!unreadCount||markingAll)return;setMarkingAll(true);const previousItems=items;const previousCount=unreadCount;setItems(current=>current.map(item=>({...item,unread:false})));setUnreadCount(0);try{const response=await fetch('/api/provider/support/notifications/read-all',{method:'POST'});if(!response.ok)throw new Error();setError('')}catch{setItems(previousItems);setUnreadCount(previousCount);setError('تعذر تحديد الإشعارات كمقروءة. حاول مرة أخرى.')}finally{setMarkingAll(false)}}
 return <div className="relative" ref={panelRef}><button ref={bellRef} type="button" aria-label="إشعارات الدعم" aria-expanded={open} aria-controls={panelId} onClick={()=>setOpen(value=>!value)} className="relative grid size-10 place-items-center rounded-xl border border-cyan-300/15 bg-[#07111f] text-lg focus:outline-none focus:ring-2 focus:ring-cyan-300/25">🔔{unreadCount>0?<span className="absolute -left-2 -top-2 min-w-5 rounded-full bg-cyan-300 px-1.5 py-0.5 text-[10px] font-black text-slate-950">{unreadCount>99?'99+':unreadCount}</span>:null}</button>{open?<section id={panelId} aria-label="قائمة إشعارات الدعم" className="fixed inset-x-3 top-20 z-[9000] max-h-[75vh] overflow-y-auto rounded-[24px] border border-cyan-300/15 bg-[#07111f] p-4 shadow-2xl sm:absolute sm:inset-x-auto sm:left-0 sm:top-12 sm:w-[390px]"><header className="flex items-center justify-between gap-3"><h2 className="font-black">إشعارات الدعم</h2><button type="button" disabled={!unreadCount||markingAll} onClick={()=>void markAll()} className="text-xs font-bold text-cyan-200 disabled:opacity-40">تحديد الكل كمقروء</button></header>{error?<p className="mt-3 rounded-xl border border-red-300/15 bg-red-300/[0.06] p-3 text-xs text-red-200">{error}</p>:null}<div className="mt-3 space-y-2">{loading?<div className="h-28 animate-pulse rounded-xl bg-white/[0.05]"/>:items.length===0?<p className="py-8 text-center text-sm text-slate-400">لا توجد إشعارات دعم حتى الآن</p>:items.map(item=><button key={item.event_key} type="button" disabled={openingKey===item.event_key} onClick={()=>void openNotification(item)} className={`w-full min-w-0 rounded-xl border p-3 text-right ${item.unread?'border-cyan-300/20 bg-cyan-300/[0.08]':'border-white/10 bg-white/[0.025]'}`}><span className="text-xs font-black text-cyan-200">{item.event_type==='ticket_created'?'تذكرة جديدة':'رد جديد من العميل'}</span><p className="mt-1 truncate text-sm font-bold">{item.ticket_number} — {item.title}</p><p className="mt-1 truncate text-xs text-slate-400">{item.organization_name}</p>{item.preview?<p className="mt-2 line-clamp-2 text-xs text-slate-400">{item.preview}</p>:null}<time className="mt-2 block text-[11px] text-slate-500">{new Date(item.activity_at).toLocaleString('ar-SA')}</time></button>)}</div></section>:null}</div>
}
