'use client'
import { useRouter } from 'next/navigation'
import { useState } from 'react'
import { AdminDarkSelect } from '@/components/admin-dark-select'
export function DeveloperUsersFilters({ initial }: { initial: { search: string; status: string; role: string; tenant: string } }) {
 const router = useRouter(); const [search, setSearch] = useState(initial.search); const [status, setStatus] = useState(initial.status); const [role, setRole] = useState(initial.role); const [tenant, setTenant] = useState(initial.tenant)
 const navigate = () => { const query = new URLSearchParams(); if (search.trim()) query.set('search', search.trim()); if (status) query.set('status', status); if (role) query.set('role', role); if (tenant.trim()) query.set('tenant', tenant.trim()); router.push(`/developer/users${query.size ? `?${query}` : ''}`) }
 const reset = () => { setSearch(''); setStatus(''); setRole(''); setTenant(''); router.push('/developer/users') }
 return <section className="rounded-[24px] border border-white/10 bg-white/[0.035] p-4 sm:p-5"><form onSubmit={(event) => { event.preventDefault(); navigate() }} className="space-y-4"><div className="grid gap-3 sm:grid-cols-[minmax(0,1fr)_auto_auto]"><label className="min-w-0"><span className="mb-2 block text-xs font-bold text-slate-400">البحث</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="الاسم، Username، البريد أو الجوال" className="h-12 w-full rounded-2xl border border-white/10 bg-[#040b14] px-4 text-sm outline-none focus:border-cyan-300/40" /></label><button className="h-12 self-end rounded-2xl bg-cyan-300 px-6 text-sm font-black text-slate-950">بحث</button><button type="button" onClick={reset} className="h-12 self-end rounded-2xl border border-white/10 px-5 text-sm font-bold text-slate-300">مسح الفلاتر</button></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><label><span className="mb-2 block text-xs font-bold text-slate-400">حالة الحساب</span><AdminDarkSelect value={status} onChange={setStatus} options={[{ value: '', label: 'كل الحالات' }, { value: 'active', label: 'نشط' }, { value: 'inactive', label: 'موقوف' }]} /></label><label><span className="mb-2 block text-xs font-bold text-slate-400">الدور</span><AdminDarkSelect value={role} onChange={setRole} options={[{ value: '', label: 'كل الأدوار' }, { value: 'admin', label: 'إداري' }, { value: 'manager', label: 'مدير' }, { value: 'employee', label: 'موظف' }]} /></label><label><span className="mb-2 block text-xs font-bold text-slate-400">المنشأة</span><input value={tenant} onChange={(event) => setTenant(event.target.value)} placeholder="اسم المنشأة" className="h-12 w-full rounded-2xl border border-white/10 bg-[#040b14] px-4 text-sm outline-none focus:border-cyan-300/40" /></label></div></form></section>
}
