-- P2D.21R AUTHORIZATION COLUMN ACL CANONICAL CONTRACT
-- DO NOT EXECUTE.
-- Static reference only: VALUES, CTE, and SELECT.

WITH authorization_column_acl_contract(
    schema_name,
    table_name,
    column_name,
    grantee,
    privilege_type,
    is_grantable,
    contract_classification
) AS (
    VALUES
        ('public'::text, 'branches'::text, 'deleted_at'::text,
         'afex_function_owner'::text, 'SELECT'::text, false,
         'CORE_V2_AUTHORIZATION_EVIDENCE'::text),
        ('public', 'branches', 'id',
         'afex_function_owner', 'SELECT', false,
         'CORE_V2_AUTHORIZATION_EVIDENCE'),
        ('public', 'branches', 'is_active',
         'afex_function_owner', 'SELECT', false,
         'CORE_V2_AUTHORIZATION_EVIDENCE'),
        ('public', 'branches', 'tenant_id',
         'afex_function_owner', 'SELECT', false,
         'CORE_V2_AUTHORIZATION_EVIDENCE'),
        ('public', 'profiles', 'branch_id',
         'afex_function_owner', 'SELECT', false,
         'CORE_V2_AUTHORIZATION_EVIDENCE'),
        ('public', 'profiles', 'id',
         'afex_function_owner', 'SELECT', false,
         'CORE_V2_AUTHORIZATION_EVIDENCE'),
        ('public', 'profiles', 'is_active',
         'afex_function_owner', 'SELECT', false,
         'CORE_V2_AUTHORIZATION_EVIDENCE'),
        ('public', 'profiles', 'role',
         'afex_function_owner', 'SELECT', false,
         'CORE_V2_AUTHORIZATION_EVIDENCE'),
        ('public', 'profiles', 'tenant_id',
         'afex_function_owner', 'SELECT', false,
         'CORE_V2_AUTHORIZATION_EVIDENCE'),
        ('public', 'profiles', 'updated_at',
         'afex_function_owner', 'SELECT', false,
         'CORE_V2_AUTHORIZATION_EVIDENCE'),
        ('public', 'tenants', 'id',
         'afex_function_owner', 'SELECT', false,
         'CORE_V2_AUTHORIZATION_EVIDENCE'),
        ('public', 'profiles', 'branch_id',
         'authenticated', 'SELECT', false,
         'LEGACY_AUTHENTICATED_APPLICATION_KEEP'),
        ('public', 'profiles', 'contact_email',
         'authenticated', 'SELECT', false,
         'LEGACY_AUTHENTICATED_APPLICATION_KEEP'),
        ('public', 'profiles', 'contact_email',
         'authenticated', 'UPDATE', false,
         'LEGACY_AUTHENTICATED_APPLICATION_KEEP'),
        ('public', 'profiles', 'full_name',
         'authenticated', 'SELECT', false,
         'LEGACY_AUTHENTICATED_APPLICATION_KEEP'),
        ('public', 'profiles', 'full_name',
         'authenticated', 'UPDATE', false,
         'LEGACY_AUTHENTICATED_APPLICATION_KEEP'),
        ('public', 'profiles', 'id',
         'authenticated', 'SELECT', false,
         'LEGACY_AUTHENTICATED_APPLICATION_KEEP'),
        ('public', 'profiles', 'is_active',
         'authenticated', 'SELECT', false,
         'LEGACY_AUTHENTICATED_APPLICATION_KEEP'),
        ('public', 'profiles', 'phone',
         'authenticated', 'SELECT', false,
         'LEGACY_AUTHENTICATED_APPLICATION_KEEP'),
        ('public', 'profiles', 'phone',
         'authenticated', 'UPDATE', false,
         'LEGACY_AUTHENTICATED_APPLICATION_KEEP'),
        ('public', 'profiles', 'role',
         'authenticated', 'SELECT', false,
         'LEGACY_AUTHENTICATED_APPLICATION_KEEP'),
        ('public', 'profiles', 'tenant_id',
         'authenticated', 'SELECT', false,
         'LEGACY_AUTHENTICATED_APPLICATION_KEEP'),
        ('public', 'profiles', 'tenant_name',
         'authenticated', 'SELECT', false,
         'LEGACY_AUTHENTICATED_APPLICATION_KEEP'),
        ('public', 'profiles', 'updated_at',
         'authenticated', 'UPDATE', false,
         'LEGACY_AUTHENTICATED_APPLICATION_KEEP'),
        ('public', 'profiles', 'username',
         'authenticated', 'SELECT', false,
         'LEGACY_AUTHENTICATED_APPLICATION_KEEP')
)
SELECT
    schema_name,
    table_name,
    column_name,
    grantee,
    privilege_type,
    is_grantable,
    contract_classification
FROM authorization_column_acl_contract
ORDER BY
    schema_name,
    table_name,
    column_name,
    grantee,
    privilege_type,
    is_grantable,
    contract_classification;
